import { buildXlsxWorkbook, type SheetModel } from "./quote-xlsx";

export const supplierPoSheets: SheetModel[] = [
  {
    name: "Supplier PO",
    rows: [
      ["Lattice Supplier Purchase Order Template"],
      ["Send to Chinese machine shop after customer quote acceptance, final file release, and supplier selection."],
      [],
      ["PO number", "LPO-[YYYY]-[####]"],
      ["PO date", "[YYYY-MM-DD]"],
      ["Supplier / factory", "[Chinese machine shop legal name]"],
      ["Supplier contact", "[Name, email, WeChat, phone]"],
      ["Lattice contact", "William Paik / will@latticeos.co"],
      ["Customer project", "[Customer / project name]"],
      ["Related customer quote", "LQ-[####]"],
      ["Incoterms / shipping terms", "[EXW / FOB / DDP / DAP / other]"],
      ["Currency", "USD"],
      ["Payment terms", "[Deposit / balance / net terms / wire instructions]"],
      ["Required ship date", "[YYYY-MM-DD or TBD]"],
      ["Destination / consignee", "[Lattice, customer, freight forwarder, or consolidation address]"],
      [],
      ["Item", "Part / file package", "Process", "Material", "Finish", "Drawing revision", "Qty", "Supplier unit price", "Supplier subtotal", "Lead time", "Inspection / documents", "Supplier notes"],
      [1, "[part-name.step / drawing Rev A]", "[CNC machining]", "[6061-T6 aluminum]", "[Clear anodize]", "[Rev A]", 0, 0, 0, "[X business days]", "[Dimensional report / material cert / photos]", "[DFM or process notes]"],
      [2, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [3, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [4, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [5, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [6, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [7, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [8, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [9, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [10, "", "", "", "", "", 0, 0, 0, "", "", ""],
      [],
      ["Part production subtotal", 0],
      ["Tooling / setup", 0],
      ["Domestic China freight / handling", 0],
      ["Export packing / documentation", 0],
      ["Other supplier charges", 0],
      ["Supplier PO total", 0],
      [],
      ["Release checklist", "Status / notes"],
      ["Final CAD and drawings attached", "[Yes / No / files linked]"],
      ["Customer revision and quantity match quote", "[Yes / No]"],
      ["Material, finish, tolerance, and inspection scope confirmed", "[Yes / No]"],
      ["DFM changes approved by customer", "[Yes / No / N/A]"],
      ["Packaging, labeling, and shipment handoff confirmed", "[Yes / No]"],
    ],
  },
  {
    name: "Supplier Terms",
    rows: [
      ["Supplier PO Terms"],
      [],
      ["Clause", "Standard language"],
      ["File control", "Supplier must manufacture only from the final CAD, drawing, revision, quantity, and notes listed on this PO or in the attached release package."],
      ["Change control", "Supplier may not change material, finish, process, tolerance approach, quantity, shipment method, or subcontracted process without written Lattice approval."],
      ["Quality", "Supplier must inspect all critical dimensions and provide requested inspection records, photos, material certificates, or finish certificates before shipment when listed on the PO."],
      ["Nonconformance", "Supplier must notify Lattice before shipment if any part does not meet drawing, finish, cosmetic, packing, or documentation requirements."],
      ["Confidentiality", "Customer CAD, drawings, specifications, and order information may be used only for quoting and producing this Lattice order."],
      ["Payment release", "Final payment may be held until required quality documents, photos, shipment records, and any corrective actions are complete."],
      ["Shipment", "Supplier is responsible for accurate packing list, commercial invoice support details when needed, export-ready packaging, and shipment handoff according to the agreed terms."],
    ],
  },
];

export const domesticInvoiceSheets: SheetModel[] = [
  {
    name: "Invoice",
    rows: [
      ["Lattice Domestic Customer Invoice Template"],
      ["Issue to domestic machine shop or customer after PO acceptance, shipment milestone, or agreed billing trigger."],
      [],
      ["Invoice number", "INV-[YYYY]-[####]"],
      ["Invoice date", "[YYYY-MM-DD]"],
      ["Payment due date", "[YYYY-MM-DD]"],
      ["Bill to company", "[Domestic machine shop / customer legal name]"],
      ["Bill to contact", "[Name, email, phone]"],
      ["Bill to address", "[Billing address]"],
      ["Customer PO number", "[Customer PO #]"],
      ["Related quote", "LQ-[####]"],
      ["Related Lattice order", "PO-[####]"],
      ["Payment terms", "[Net 15 / Net 30 / due on receipt / deposit-balance]"],
      ["Payment instructions", "[Wire / ACH / card / check instructions]"],
      [],
      ["Item", "Description", "Process / scope", "Qty", "Unit price", "Line total", "Tax treatment", "Notes"],
      [1, "[Part / order description]", "[CNC machining / fabrication / shipping / service]", 0, 0, 0, "[Taxable / non-taxable / resale]", "[Reference shipped parts, certs, or invoice milestone]"],
      [2, "", "", 0, 0, 0, "", ""],
      [3, "", "", 0, 0, 0, "", ""],
      [4, "", "", 0, 0, 0, "", ""],
      [5, "", "", 0, 0, 0, "", ""],
      [6, "", "", 0, 0, 0, "", ""],
      [7, "", "", 0, 0, 0, "", ""],
      [8, "", "", 0, 0, 0, "", ""],
      [9, "", "", 0, 0, 0, "", ""],
      [10, "", "", 0, 0, 0, "", ""],
      [],
      ["Subtotal", 0],
      ["Shipping / freight", 0],
      ["Tariffs / duties / customs", 0],
      ["Sales tax", 0],
      ["Other charges", 0],
      ["Amount due", 0],
      [],
      ["Remittance note", "Please reference invoice number, customer PO number, and Lattice order number with payment."],
      ["AP follow-up owner", "[Lattice owner]"],
      ["Internal collection notes", "[Not customer-facing if exported as PDF]"],
    ],
  },
  {
    name: "Invoice Terms",
    rows: [
      ["Domestic Invoice Terms"],
      [],
      ["Clause", "Standard language"],
      ["Payment", "Payment is due by the payment due date and should reference the invoice number, related quote, order number, and customer PO number."],
      ["Scope", "Invoice line items reflect the accepted quote, customer PO, shipment milestone, or approved change order listed on the invoice."],
      ["Taxes and duties", "Sales tax, tariffs, duties, customs brokerage, and freight charges are billed only when listed on the invoice or required by the accepted purchasing terms."],
      ["Disputes", "Invoice disputes must identify the affected line item, reason, and supporting documentation so Lattice can reconcile the order record."],
      ["Late payment", "Late payment handling follows the accepted customer terms or separately executed purchasing agreement."],
      ["Confidentiality", "Pricing, supplier routing, and manufacturing records are confidential to Lattice and the invoiced customer unless otherwise agreed in writing."],
    ],
  },
];

export function buildSupplierPurchaseOrderTemplateXlsx() {
  return buildXlsxWorkbook(supplierPoSheets);
}

export function buildDomesticInvoiceTemplateXlsx() {
  return buildXlsxWorkbook(domesticInvoiceSheets);
}
