export type CncMaterialFamily =
  | "Aluminum"
  | "Stainless steel"
  | "Steel"
  | "Tool steel"
  | "Titanium"
  | "Nickel / precision alloy"
  | "Copper / brass / bronze"
  | "Cast iron"
  | "Magnesium / zinc"
  | "Plastic / polymer"
  | "Composite";

export type CncMaterialSource = "Fictiv" | "Hubs" | "Xometry";

export type CncMaterialLibraryEntry = {
  label: string;
  value: string;
  family: CncMaterialFamily;
  unsNumber: string;
  composition: string;
  compositionFormula: string;
  sources: CncMaterialSource[];
};

type CncMaterialDetails = Pick<CncMaterialLibraryEntry, "unsNumber" | "composition"> & {
  compositionFormula?: string;
};

function slug(label: string) {
  return label
    .toLowerCase()
    .replace(/\+/g, " plus ")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

const materialDetails: Record<string, CncMaterialDetails> = {
  "6061-T6 Aluminum": { unsNumber: "UNS A96061", composition: "Al, 0.8-1.2 Mg, 0.4-0.8 Si, 0.15-0.4 Cu, 0.04-0.35 Cr" },
  "6061-T651 Aluminum": { unsNumber: "UNS A96061", composition: "Al, 0.8-1.2 Mg, 0.4-0.8 Si, 0.15-0.4 Cu, 0.04-0.35 Cr" },
  "6063 Aluminum": { unsNumber: "UNS A96063", composition: "Al, 0.45-0.9 Mg, 0.2-0.6 Si, max 0.35 Fe" },
  "6063-T5 Aluminum": { unsNumber: "UNS A96063", composition: "Al, 0.45-0.9 Mg, 0.2-0.6 Si, max 0.35 Fe" },
  "6060 Aluminum": { unsNumber: "UNS A96060", composition: "Al, 0.35-0.6 Mg, 0.3-0.6 Si, max 0.3 Fe" },
  "6082 Aluminum": { unsNumber: "UNS A96082", composition: "Al, 0.6-1.2 Mg, 0.7-1.3 Si, 0.4-1.0 Mn" },
  "6082-T651 Aluminum": { unsNumber: "UNS A96082", composition: "Al, 0.6-1.2 Mg, 0.7-1.3 Si, 0.4-1.0 Mn" },
  "7075-T6 Aluminum": { unsNumber: "UNS A97075", composition: "Al, 5.1-6.1 Zn, 2.1-2.9 Mg, 1.2-2.0 Cu, 0.18-0.28 Cr" },
  "7075-T651 Aluminum": { unsNumber: "UNS A97075", composition: "Al, 5.1-6.1 Zn, 2.1-2.9 Mg, 1.2-2.0 Cu, 0.18-0.28 Cr" },
  "7075-T7351 Aluminum": { unsNumber: "UNS A97075", composition: "Al, 5.1-6.1 Zn, 2.1-2.9 Mg, 1.2-2.0 Cu, 0.18-0.28 Cr" },
  "7050 Aluminum": { unsNumber: "UNS A97050", composition: "Al, 5.7-6.7 Zn, 1.9-2.6 Mg, 2.0-2.6 Cu, 0.08-0.15 Zr" },
  "2024 Aluminum": { unsNumber: "UNS A92024", composition: "Al, 3.8-4.9 Cu, 1.2-1.8 Mg, 0.3-0.9 Mn" },
  "2024-T351 Aluminum": { unsNumber: "UNS A92024", composition: "Al, 3.8-4.9 Cu, 1.2-1.8 Mg, 0.3-0.9 Mn" },
  "2014 Aluminum": { unsNumber: "UNS A92014", composition: "Al, 3.9-5.0 Cu, 0.4-1.2 Si, 0.4-1.2 Mn, 0.2-0.8 Mg" },
  "2017A Aluminum": { unsNumber: "UNS A92017", composition: "Al, 3.5-4.5 Cu, 0.4-1.0 Mg, 0.4-1.0 Mn" },
  "2007 Aluminum": { unsNumber: "UNS N/A", composition: "Al-Cu-Pb free-machining alloy, typically 3.3-4.6 Cu and 0.8-1.5 Pb" },
  "3003 Aluminum": { unsNumber: "UNS A93003", composition: "Al, 1.0-1.5 Mn, 0.05-0.2 Cu" },
  "5052 Aluminum": { unsNumber: "UNS A95052", composition: "Al, 2.2-2.8 Mg, 0.15-0.35 Cr" },
  "5083-H111 Aluminum": { unsNumber: "UNS A95083", composition: "Al, 4.0-4.9 Mg, 0.4-1.0 Mn, 0.05-0.25 Cr" },
  "5251 Aluminum": { unsNumber: "UNS A95251", composition: "Al, 1.7-2.4 Mg, 0.1-0.5 Mn, max 0.15 Cr" },
  "5754 Aluminum": { unsNumber: "UNS A95754", composition: "Al, 2.6-3.6 Mg, max 0.5 Mn, max 0.3 Cr" },
  "MIC6 Aluminum": { unsNumber: "UNS N/A", composition: "Cast aluminum tooling plate, Al-Mg alloy with proprietary chemistry" },

  "303 Stainless Steel": { unsNumber: "UNS S30300", composition: "Fe, 17-19 Cr, 8-10 Ni, sulfur/selenium added for machinability" },
  "304 Stainless Steel": { unsNumber: "UNS S30400", composition: "Fe, 18-20 Cr, 8-10.5 Ni, max 2 Mn" },
  "304/304L Stainless Steel": { unsNumber: "UNS S30400 / S30403", composition: "Fe, 18-20 Cr, 8-12 Ni; 304L has lower carbon" },
  "304L Stainless Steel": { unsNumber: "UNS S30403", composition: "Fe, 18-20 Cr, 8-12 Ni, max 0.03 C" },
  "316 Stainless Steel": { unsNumber: "UNS S31600", composition: "Fe, 16-18 Cr, 10-14 Ni, 2-3 Mo" },
  "316/316L Stainless Steel": { unsNumber: "UNS S31600 / S31603", composition: "Fe, 16-18 Cr, 10-14 Ni, 2-3 Mo; 316L has lower carbon" },
  "316L Stainless Steel": { unsNumber: "UNS S31603", composition: "Fe, 16-18 Cr, 10-14 Ni, 2-3 Mo, max 0.03 C" },
  "316Ti Stainless Steel": { unsNumber: "UNS S31635", composition: "Fe, 16-18 Cr, 10-14 Ni, 2-3 Mo, Ti stabilized" },
  "301 Stainless Steel": { unsNumber: "UNS S30100", composition: "Fe, 16-18 Cr, 6-8 Ni, max 2 Mn" },
  "410 Stainless Steel": { unsNumber: "UNS S41000", composition: "Fe, 11.5-13.5 Cr, max 0.15 C" },
  "416 Stainless Steel": { unsNumber: "UNS S41600", composition: "Fe, 12-14 Cr, sulfur added for free machining" },
  "420 Stainless Steel": { unsNumber: "UNS S42000", composition: "Fe, 12-14 Cr, min 0.15 C" },
  "420C Stainless Steel": { unsNumber: "UNS S42000", composition: "Fe, 12-14 Cr, high-carbon martensitic stainless steel" },
  "430 Stainless Steel": { unsNumber: "UNS S43000", composition: "Fe, 16-18 Cr, max 0.12 C" },
  "440C Stainless Steel": { unsNumber: "UNS S44004", composition: "Fe, 16-18 Cr, 0.95-1.2 C, max 0.75 Mo" },
  "15-5 Stainless Steel": { unsNumber: "UNS S15500", composition: "Fe, 14-15.5 Cr, 3.5-5.5 Ni, 2.5-4.5 Cu, Nb/Cb" },
  "17-4 PH Stainless Steel": { unsNumber: "UNS S17400", composition: "Fe, 15-17.5 Cr, 3-5 Ni, 3-5 Cu, Nb/Cb" },
  "18-8 Stainless Steel": { unsNumber: "UNS N/A", composition: "300-series austenitic stainless, nominal 18 Cr and 8 Ni" },
  "2205 Duplex Stainless Steel": { unsNumber: "UNS S32205 / S31803", composition: "Fe, 21-23 Cr, 4.5-6.5 Ni, 2.5-3.5 Mo, N" },
  "Nitronic 60 Stainless Steel": { unsNumber: "UNS S21800", composition: "Fe, 16-18 Cr, 8-9 Ni, 7-9 Mn, 3.5-4.5 Si" },
  "SS 300 series": { unsNumber: "UNS N/A", composition: "300-series austenitic stainless steels, Cr-Ni family" },
  "SS 303": { unsNumber: "UNS S30300", composition: "Fe, 17-19 Cr, 8-10 Ni, sulfur/selenium added for machinability" },
  "SS 304": { unsNumber: "UNS S30400", composition: "Fe, 18-20 Cr, 8-10.5 Ni, max 2 Mn" },
  "SS 316": { unsNumber: "UNS S31600", composition: "Fe, 16-18 Cr, 10-14 Ni, 2-3 Mo" },

  "1018 Steel": { unsNumber: "UNS G10180", composition: "Fe, 0.15-0.20 C, 0.60-0.90 Mn" },
  "1215 Steel": { unsNumber: "UNS G12150", composition: "Fe, max 0.09 C, 0.75-1.05 Mn, 0.26-0.35 S, 0.04-0.09 P" },
  "4130 Steel": { unsNumber: "UNS G41300", composition: "Fe, 0.28-0.33 C, 0.8-1.1 Cr, 0.15-0.25 Mo" },
  "4140 Steel": { unsNumber: "UNS G41400", composition: "Fe, 0.38-0.43 C, 0.8-1.1 Cr, 0.15-0.25 Mo" },
  "4340 Steel": { unsNumber: "UNS G43400", composition: "Fe, 0.38-0.43 C, 1.65-2.0 Ni, 0.7-0.9 Cr, 0.2-0.3 Mo" },
  "A36 Steel": { unsNumber: "UNS K02600", composition: "Fe, low-carbon structural steel, max 0.26 C with Mn, P, S, Si limits" },
  "A514 Steel": { unsNumber: "UNS N/A", composition: "Quenched and tempered alloy steel plate, low-carbon steel with Cr, Mo, Ni, V/Ti/B additions by grade" },
  "1.7131 / 16MnCr5 Alloy Steel": { unsNumber: "UNS N/A", composition: "Fe, 0.14-0.19 C, 1.0-1.3 Mn, 0.8-1.1 Cr" },
  "1.7139 / 16MnCrS5 Alloy Steel": { unsNumber: "UNS N/A", composition: "Fe, 0.14-0.19 C, 1.0-1.3 Mn, 0.8-1.1 Cr, sulfurized" },
  "1.7227 / 42CrMoS4 Alloy Steel": { unsNumber: "UNS N/A", composition: "Fe, 0.38-0.45 C, 0.9-1.2 Cr, 0.15-0.3 Mo, sulfurized" },
  "1.6580 / 30CrNiMo8 Alloy Steel": { unsNumber: "UNS N/A", composition: "Fe, 0.26-0.34 C, 1.8-2.2 Ni, 1.8-2.2 Cr, 0.3-0.5 Mo" },
  "1.6582 / 34CrNiMo6 Alloy Steel": { unsNumber: "UNS N/A", composition: "Fe, 0.3-0.38 C, 1.3-1.7 Ni, 1.3-1.7 Cr, 0.15-0.3 Mo" },

  "A2 Tool Steel": { unsNumber: "UNS T30102", composition: "Fe, 0.95-1.05 C, 4.75-5.5 Cr, 0.9-1.4 Mo, 0.15-0.5 V" },
  "O1 Tool Steel": { unsNumber: "UNS T31501", composition: "Fe, 0.85-1.0 C, 1.0-1.4 Mn, 0.4-0.6 Cr, 0.4-0.6 W" },

  "Titanium Grade 2": { unsNumber: "UNS R50400", composition: "Commercially pure Ti, max 0.3 Fe, max 0.25 O" },
  "Titanium Grade 5": { unsNumber: "UNS R56400", composition: "Ti, 5.5-6.75 Al, 3.5-4.5 V" },

  "Inconel 625": { unsNumber: "UNS N06625", composition: "Ni, 20-23 Cr, 8-10 Mo, 3.15-4.15 Nb+Ta, max 5 Fe" },
  "Invar": { unsNumber: "UNS K93600", composition: "Fe-Ni alloy, nominal 36 Ni with low thermal expansion" },
  "Invar 36": { unsNumber: "UNS K93600", composition: "Fe-Ni alloy, nominal 36 Ni with low thermal expansion" },
  "Kovar": { unsNumber: "UNS K94610", composition: "Fe, 28.5-29.5 Ni, 16.8-17.8 Co" },

  "Brass 260": { unsNumber: "UNS C26000", composition: "Cu, 28.5-31.5 Zn" },
  "Brass 360": { unsNumber: "UNS C36000", composition: "Cu, 35.5-37.0 Zn, 2.5-3.7 Pb" },
  "Brass C360": { unsNumber: "UNS C36000", composition: "Cu, 35.5-37.0 Zn, 2.5-3.7 Pb" },
  "Bronze 932": { unsNumber: "UNS C93200", composition: "Cu, 6.3-7.5 Sn, 6.0-8.0 Pb, 2.0-4.0 Zn" },
  "Bronze C932": { unsNumber: "UNS C93200", composition: "Cu, 6.3-7.5 Sn, 6.0-8.0 Pb, 2.0-4.0 Zn" },
  "Copper 101": { unsNumber: "UNS C10100", composition: "Oxygen-free electronic copper, min 99.99 Cu" },
  "Copper 110": { unsNumber: "UNS C11000", composition: "Electrolytic tough pitch copper, min 99.9 Cu" },
  "Copper C110": { unsNumber: "UNS C11000", composition: "Electrolytic tough pitch copper, min 99.9 Cu" },

  "Cast Iron": { unsNumber: "UNS N/A", composition: "Fe-C-Si cast alloy, typically 2.5-4.0 C and 1.0-3.0 Si" },
  Magnesium: { unsNumber: "UNS N/A", composition: "Mg alloy family; exact chemistry depends on selected grade" },
  Zinc: { unsNumber: "UNS N/A", composition: "Zn alloy family; exact chemistry depends on selected grade" },

  ABS: { unsNumber: "UNS N/A", composition: "Acrylonitrile butadiene styrene thermoplastic" },
  "Acetal (POM)": { unsNumber: "UNS N/A", composition: "Polyoxymethylene engineering thermoplastic" },
  "Acetal Copolymer (POM-C)": { unsNumber: "UNS N/A", composition: "POM copolymer, acetal copolymer thermoplastic" },
  "Acetal Copolymer (POM-C) ESD": { unsNumber: "UNS N/A", composition: "ESD-modified POM copolymer thermoplastic" },
  "Acetal Copolymer (POM-C) FDA": { unsNumber: "UNS N/A", composition: "FDA-grade POM copolymer thermoplastic" },
  "Acetal Homopolymer (POM-H)": { unsNumber: "UNS N/A", composition: "POM homopolymer acetal thermoplastic" },
  Acrylic: { unsNumber: "UNS N/A", composition: "Polymethyl methacrylate (PMMA)" },
  Delrin: { unsNumber: "UNS N/A", composition: "Acetal homopolymer, POM-H" },
  "Delrin 100 AF": { unsNumber: "UNS N/A", composition: "PTFE-filled acetal homopolymer, POM-H" },
  "Delrin 150": { unsNumber: "UNS N/A", composition: "Acetal homopolymer, POM-H" },
  "Delrin 30% Glass Filled": { unsNumber: "UNS N/A", composition: "Glass-filled acetal homopolymer, POM-H" },
  FR4: { unsNumber: "UNS N/A", composition: "Woven glass-reinforced epoxy laminate" },
  "Garolite G-10": { unsNumber: "UNS N/A", composition: "Woven glass-reinforced epoxy laminate" },
  "Garolite G-10 / FR4": { unsNumber: "UNS N/A", composition: "Woven glass-reinforced epoxy laminate" },
  "Garolite G-11 / FR5": { unsNumber: "UNS N/A", composition: "High-temperature woven glass epoxy laminate" },
  HDPE: { unsNumber: "UNS N/A", composition: "High-density polyethylene" },
  Nylon: { unsNumber: "UNS N/A", composition: "Polyamide thermoplastic" },
  "Nylon 6/6": { unsNumber: "UNS N/A", composition: "Polyamide 6/6 thermoplastic" },
  PEEK: { unsNumber: "UNS N/A", composition: "Polyether ether ketone thermoplastic" },
  "PEEK 30% Glass Filled": { unsNumber: "UNS N/A", composition: "30% glass-filled polyether ether ketone" },
  "PEEK / USP Class VI TECAPEEK": { unsNumber: "UNS N/A", composition: "Medical-grade polyether ether ketone" },
  PEI: { unsNumber: "UNS N/A", composition: "Polyetherimide thermoplastic" },
  PET: { unsNumber: "UNS N/A", composition: "Polyethylene terephthalate thermoplastic" },
  "PMMA (Acrylic)": { unsNumber: "UNS N/A", composition: "Polymethyl methacrylate" },
  Polycarbonate: { unsNumber: "UNS N/A", composition: "Polycarbonate thermoplastic" },
  Polyethylene: { unsNumber: "UNS N/A", composition: "Polyethylene thermoplastic" },
  Polypropylene: { unsNumber: "UNS N/A", composition: "Polypropylene thermoplastic" },
  "POM (Delrin/Acetal)": { unsNumber: "UNS N/A", composition: "Polyoxymethylene acetal thermoplastic" },
  PPS: { unsNumber: "UNS N/A", composition: "Polyphenylene sulfide thermoplastic" },
  PPSU: { unsNumber: "UNS N/A", composition: "Polyphenylsulfone thermoplastic" },
  PTFE: { unsNumber: "UNS N/A", composition: "Polytetrafluoroethylene fluoropolymer" },
  "PTFE (Teflon)": { unsNumber: "UNS N/A", composition: "Polytetrafluoroethylene fluoropolymer" },
  PVC: { unsNumber: "UNS N/A", composition: "Polyvinyl chloride thermoplastic" },
  Torlon: { unsNumber: "UNS N/A", composition: "Polyamide-imide thermoplastic" },
  UHMW: { unsNumber: "UNS N/A", composition: "Ultra-high-molecular-weight polyethylene" },
  "UHMW PE": { unsNumber: "UNS N/A", composition: "Ultra-high-molecular-weight polyethylene" },
  Ultem: { unsNumber: "UNS N/A", composition: "Polyetherimide thermoplastic" },
  "ULTEM 1000": { unsNumber: "UNS N/A", composition: "Unfilled polyetherimide thermoplastic" },
  "ULTEM 2300": { unsNumber: "UNS N/A", composition: "30% glass-filled polyetherimide thermoplastic" },
};

const materialCompositionFormulas: Record<string, string> = {
  "6061-T6 Aluminum": "AlMg1SiCu",
  "6061-T651 Aluminum": "AlMg1SiCu",
  "6063 Aluminum": "AlMg0.7Si",
  "6063-T5 Aluminum": "AlMg0.7Si",
  "6060 Aluminum": "AlMgSi",
  "6082 Aluminum": "AlSi1MgMn",
  "6082-T651 Aluminum": "AlSi1MgMn",
  "7075-T6 Aluminum": "AlZn5.5MgCu",
  "7075-T651 Aluminum": "AlZn5.5MgCu",
  "7075-T7351 Aluminum": "AlZn5.5MgCu",
  "7050 Aluminum": "AlZn6CuMgZr",
  "2024 Aluminum": "AlCu4Mg1",
  "2024-T351 Aluminum": "AlCu4Mg1",
  "2014 Aluminum": "AlCu4SiMg",
  "2017A Aluminum": "AlCu4MgSi",
  "2007 Aluminum": "AlCu4PbMgMn",
  "3003 Aluminum": "AlMn1Cu",
  "5052 Aluminum": "AlMg2.5",
  "5083-H111 Aluminum": "AlMg4.5Mn",
  "5251 Aluminum": "AlMg2",
  "5754 Aluminum": "AlMg3",
  "MIC6 Aluminum": "Cast Al tooling plate",

  "303 Stainless Steel": "X8CrNiS18-9",
  "304 Stainless Steel": "X5CrNi18-10",
  "304/304L Stainless Steel": "X5CrNi18-10 / X2CrNi19-11",
  "304L Stainless Steel": "X2CrNi19-11",
  "316 Stainless Steel": "X5CrNiMo17-12-2",
  "316/316L Stainless Steel": "X5CrNiMo17-12-2 / X2CrNiMo17-12-2",
  "316L Stainless Steel": "X2CrNiMo17-12-2",
  "316Ti Stainless Steel": "X6CrNiMoTi17-12-2",
  "301 Stainless Steel": "X10CrNi18-8",
  "410 Stainless Steel": "X12Cr13",
  "416 Stainless Steel": "X12CrS13",
  "420 Stainless Steel": "X20Cr13",
  "420C Stainless Steel": "X46Cr13",
  "430 Stainless Steel": "X6Cr17",
  "440C Stainless Steel": "X105CrMo17",
  "15-5 Stainless Steel": "15Cr-5Ni-3Cu PH",
  "17-4 PH Stainless Steel": "17Cr-4Ni-4Cu PH",
  "18-8 Stainless Steel": "18Cr8Ni",
  "2205 Duplex Stainless Steel": "X2CrNiMoN22-5-3",
  "Nitronic 60 Stainless Steel": "FeCr18Mn8Ni8Si4N",
  "SS 300 series": "CrNi austenitic stainless",
  "SS 303": "X8CrNiS18-9",
  "SS 304": "X5CrNi18-10",
  "SS 316": "X5CrNiMo17-12-2",

  "1018 Steel": "C18 / FeMnC",
  "1215 Steel": "Free-cutting FeMnSPb-free",
  "4130 Steel": "25CrMo4",
  "4140 Steel": "42CrMo4",
  "4340 Steel": "34CrNiMo6",
  "A36 Steel": "Low-carbon structural steel",
  "A514 Steel": "Q&T alloy steel",
  "1.7131 / 16MnCr5 Alloy Steel": "16MnCr5",
  "1.7139 / 16MnCrS5 Alloy Steel": "16MnCrS5",
  "1.7227 / 42CrMoS4 Alloy Steel": "42CrMoS4",
  "1.6580 / 30CrNiMo8 Alloy Steel": "30CrNiMo8",
  "1.6582 / 34CrNiMo6 Alloy Steel": "34CrNiMo6",
  "A2 Tool Steel": "X100CrMoV5",
  "O1 Tool Steel": "90MnCrV8",
  "Titanium Grade 2": "Ti Grade 2",
  "Titanium Grade 5": "Ti6Al4V",
  "Inconel 625": "NiCr22Mo9Nb",
  Invar: "FeNi36",
  "Invar 36": "FeNi36",
  Kovar: "FeNi29Co17",
  "Brass 260": "CuZn30",
  "Brass 360": "CuZn36Pb3",
  "Brass C360": "CuZn36Pb3",
  "Bronze 932": "CuSn7Zn4Pb7",
  "Bronze C932": "CuSn7Zn4Pb7",
  "Copper 101": "Cu-OFE",
  "Copper 110": "Cu-ETP",
  "Copper C110": "Cu-ETP",
  "Cast Iron": "FeC",
  Magnesium: "Mg alloy",
  Zinc: "Zn alloy",

  ABS: "ABS",
  "Acetal (POM)": "POM",
  "Acetal Copolymer (POM-C)": "POM-C",
  "Acetal Copolymer (POM-C) ESD": "POM-C ESD",
  "Acetal Copolymer (POM-C) FDA": "POM-C FDA",
  "Acetal Homopolymer (POM-H)": "POM-H",
  Acrylic: "PMMA",
  Delrin: "POM-H",
  "Delrin 100 AF": "POM-H + PTFE",
  "Delrin 150": "POM-H",
  "Delrin 30% Glass Filled": "POM-H GF30",
  FR4: "GF epoxy FR4",
  "Garolite G-10": "GF epoxy G-10",
  "Garolite G-10 / FR4": "GF epoxy G-10/FR4",
  "Garolite G-11 / FR5": "GF epoxy G-11/FR5",
  HDPE: "HDPE",
  Nylon: "PA",
  "Nylon 6/6": "PA66",
  PEEK: "PEEK",
  "PEEK 30% Glass Filled": "PEEK GF30",
  "PEEK / USP Class VI TECAPEEK": "PEEK",
  PEI: "PEI",
  PET: "PET",
  "PMMA (Acrylic)": "PMMA",
  Polycarbonate: "PC",
  Polyethylene: "PE",
  Polypropylene: "PP",
  "POM (Delrin/Acetal)": "POM",
  PPS: "PPS",
  PPSU: "PPSU",
  PTFE: "PTFE",
  "PTFE (Teflon)": "PTFE",
  PVC: "PVC",
  Torlon: "PAI",
  UHMW: "UHMW-PE",
  "UHMW PE": "UHMW-PE",
  Ultem: "PEI",
  "ULTEM 1000": "PEI",
  "ULTEM 2300": "PEI GF30",
};

function compactComposition(composition: string) {
  return composition
    .replace(/\bthermoplastic\b/gi, "")
    .replace(/\balloy family\b/gi, "alloy")
    .replace(/\s+/g, " ")
    .trim();
}

function material(label: string, family: CncMaterialFamily, sources: CncMaterialSource[], value = slug(label)): CncMaterialLibraryEntry {
  const details = materialDetails[label] ?? {
    unsNumber: "UNS N/A",
    composition: `${family} material; composition to be confirmed by selected grade`,
    compositionFormula: family,
  };

  return {
    label,
    value,
    family,
    sources,
    ...details,
    compositionFormula: materialCompositionFormulas[label] ?? details.compositionFormula ?? compactComposition(details.composition),
  };
}

export const cncMaterialLibrary: CncMaterialLibraryEntry[] = [
  material("6061-T6 Aluminum", "Aluminum", ["Fictiv", "Hubs", "Xometry"], "al_6061_t6"),
  material("6061-T651 Aluminum", "Aluminum", ["Hubs"]),
  material("6063 Aluminum", "Aluminum", ["Fictiv", "Hubs", "Xometry"]),
  material("6063-T5 Aluminum", "Aluminum", ["Xometry"]),
  material("6060 Aluminum", "Aluminum", ["Hubs"]),
  material("6082 Aluminum", "Aluminum", ["Hubs"]),
  material("6082-T651 Aluminum", "Aluminum", ["Hubs"]),
  material("7075-T6 Aluminum", "Aluminum", ["Fictiv", "Hubs", "Xometry"]),
  material("7075-T651 Aluminum", "Aluminum", ["Hubs"]),
  material("7075-T7351 Aluminum", "Aluminum", ["Hubs"]),
  material("7050 Aluminum", "Aluminum", ["Fictiv", "Hubs", "Xometry"]),
  material("2024 Aluminum", "Aluminum", ["Fictiv", "Xometry"]),
  material("2024-T351 Aluminum", "Aluminum", ["Hubs"]),
  material("2014 Aluminum", "Aluminum", ["Hubs"]),
  material("2017A Aluminum", "Aluminum", ["Hubs"]),
  material("2007 Aluminum", "Aluminum", ["Hubs"]),
  material("3003 Aluminum", "Aluminum", ["Fictiv"]),
  material("5052 Aluminum", "Aluminum", ["Fictiv", "Hubs"]),
  material("5083-H111 Aluminum", "Aluminum", ["Hubs"]),
  material("5251 Aluminum", "Aluminum", ["Hubs"]),
  material("5754 Aluminum", "Aluminum", ["Hubs"]),
  material("MIC6 Aluminum", "Aluminum", ["Fictiv", "Hubs", "Xometry"]),

  material("303 Stainless Steel", "Stainless steel", ["Fictiv", "Hubs", "Xometry"], "ss_303"),
  material("304 Stainless Steel", "Stainless steel", ["Hubs", "Xometry"], "ss_304_full"),
  material("304/304L Stainless Steel", "Stainless steel", ["Hubs", "Xometry"]),
  material("304L Stainless Steel", "Stainless steel", ["Fictiv"]),
  material("316 Stainless Steel", "Stainless steel", ["Hubs", "Xometry"], "ss_316_full"),
  material("316/316L Stainless Steel", "Stainless steel", ["Hubs", "Xometry"]),
  material("316L Stainless Steel", "Stainless steel", ["Fictiv"]),
  material("316Ti Stainless Steel", "Stainless steel", ["Hubs"]),
  material("301 Stainless Steel", "Stainless steel", ["Hubs"]),
  material("410 Stainless Steel", "Stainless steel", ["Fictiv", "Xometry"]),
  material("416 Stainless Steel", "Stainless steel", ["Fictiv", "Hubs", "Xometry"]),
  material("420 Stainless Steel", "Stainless steel", ["Hubs", "Xometry"]),
  material("420C Stainless Steel", "Stainless steel", ["Hubs"]),
  material("430 Stainless Steel", "Stainless steel", ["Hubs"]),
  material("440C Stainless Steel", "Stainless steel", ["Fictiv", "Hubs", "Xometry"]),
  material("15-5 Stainless Steel", "Stainless steel", ["Hubs", "Xometry"]),
  material("17-4 PH Stainless Steel", "Stainless steel", ["Fictiv", "Hubs", "Xometry"]),
  material("18-8 Stainless Steel", "Stainless steel", ["Xometry"]),
  material("2205 Duplex Stainless Steel", "Stainless steel", ["Hubs"]),
  material("Nitronic 60 Stainless Steel", "Stainless steel", ["Fictiv", "Xometry"]),
  material("SS 300 series", "Stainless steel", ["Xometry"], "ss_300"),
  material("SS 303", "Stainless steel", ["Fictiv", "Hubs", "Xometry"]),
  material("SS 304", "Stainless steel", ["Hubs", "Xometry"], "ss_304"),
  material("SS 316", "Stainless steel", ["Hubs", "Xometry"], "ss_316"),

  material("1018 Steel", "Steel", ["Xometry"]),
  material("1215 Steel", "Steel", ["Hubs", "Xometry"]),
  material("4130 Steel", "Steel", ["Fictiv", "Hubs", "Xometry"]),
  material("4140 Steel", "Steel", ["Fictiv", "Hubs", "Xometry"]),
  material("4340 Steel", "Steel", ["Fictiv", "Hubs", "Xometry"]),
  material("A36 Steel", "Steel", ["Xometry"]),
  material("A514 Steel", "Steel", ["Fictiv"]),
  material("1.7131 / 16MnCr5 Alloy Steel", "Steel", ["Hubs"]),
  material("1.7139 / 16MnCrS5 Alloy Steel", "Steel", ["Hubs"]),
  material("1.7227 / 42CrMoS4 Alloy Steel", "Steel", ["Hubs"]),
  material("1.6580 / 30CrNiMo8 Alloy Steel", "Steel", ["Hubs"]),
  material("1.6582 / 34CrNiMo6 Alloy Steel", "Steel", ["Hubs"]),

  material("A2 Tool Steel", "Tool steel", ["Fictiv", "Xometry"]),
  material("O1 Tool Steel", "Tool steel", ["Xometry"]),

  material("Titanium Grade 2", "Titanium", ["Xometry"]),
  material("Titanium Grade 5", "Titanium", ["Fictiv", "Xometry"]),

  material("Inconel 625", "Nickel / precision alloy", ["Hubs"], "in_625"),
  material("Invar", "Nickel / precision alloy", ["Fictiv"]),
  material("Invar 36", "Nickel / precision alloy", ["Hubs"]),
  material("Kovar", "Nickel / precision alloy", ["Fictiv"]),

  material("Brass 260", "Copper / brass / bronze", ["Xometry"]),
  material("Brass 360", "Copper / brass / bronze", ["Fictiv"]),
  material("Brass C360", "Copper / brass / bronze", ["Hubs", "Xometry"]),
  material("Bronze 932", "Copper / brass / bronze", ["Fictiv"]),
  material("Bronze C932", "Copper / brass / bronze", ["Xometry"]),
  material("Copper 101", "Copper / brass / bronze", ["Fictiv", "Xometry"]),
  material("Copper 110", "Copper / brass / bronze", ["Fictiv"]),
  material("Copper C110", "Copper / brass / bronze", ["Hubs", "Xometry"]),

  material("Cast Iron", "Cast iron", ["Fictiv"]),
  material("Magnesium", "Magnesium / zinc", ["Fictiv"]),
  material("Zinc", "Magnesium / zinc", ["Fictiv", "Xometry"]),

  material("ABS", "Plastic / polymer", ["Fictiv", "Hubs", "Xometry"]),
  material("Acetal (POM)", "Plastic / polymer", ["Xometry"]),
  material("Acetal Copolymer (POM-C)", "Plastic / polymer", ["Hubs"]),
  material("Acetal Copolymer (POM-C) ESD", "Plastic / polymer", ["Hubs"]),
  material("Acetal Copolymer (POM-C) FDA", "Plastic / polymer", ["Hubs"]),
  material("Acetal Homopolymer (POM-H)", "Plastic / polymer", ["Hubs"]),
  material("Acrylic", "Plastic / polymer", ["Fictiv", "Xometry"]),
  material("Delrin", "Plastic / polymer", ["Fictiv"]),
  material("Delrin 100 AF", "Plastic / polymer", ["Xometry"]),
  material("Delrin 150", "Plastic / polymer", ["Fictiv", "Xometry"]),
  material("Delrin 30% Glass Filled", "Plastic / polymer", ["Fictiv"]),
  material("FR4", "Composite", ["Hubs"]),
  material("Garolite G-10", "Composite", ["Fictiv", "Hubs", "Xometry"]),
  material("Garolite G-10 / FR4", "Composite", ["Xometry"]),
  material("Garolite G-11 / FR5", "Composite", ["Xometry"]),
  material("HDPE", "Plastic / polymer", ["Fictiv", "Xometry"]),
  material("Nylon", "Plastic / polymer", ["Fictiv", "Hubs"]),
  material("Nylon 6/6", "Plastic / polymer", ["Xometry"]),
  material("PEEK", "Plastic / polymer", ["Fictiv", "Hubs", "Xometry"]),
  material("PEEK 30% Glass Filled", "Plastic / polymer", ["Fictiv", "Xometry"]),
  material("PEEK / USP Class VI TECAPEEK", "Plastic / polymer", ["Xometry"]),
  material("PEI", "Plastic / polymer", ["Hubs"]),
  material("PET", "Plastic / polymer", ["Hubs"]),
  material("PMMA (Acrylic)", "Plastic / polymer", ["Hubs"]),
  material("Polycarbonate", "Plastic / polymer", ["Fictiv", "Hubs", "Xometry"]),
  material("Polyethylene", "Plastic / polymer", ["Hubs"]),
  material("Polypropylene", "Plastic / polymer", ["Fictiv", "Hubs", "Xometry"]),
  material("POM (Delrin/Acetal)", "Plastic / polymer", ["Hubs"]),
  material("PPS", "Plastic / polymer", ["Fictiv"]),
  material("PPSU", "Plastic / polymer", ["Hubs"]),
  material("PTFE", "Plastic / polymer", ["Fictiv"]),
  material("PTFE (Teflon)", "Plastic / polymer", ["Hubs"]),
  material("PVC", "Plastic / polymer", ["Fictiv", "Hubs", "Xometry"], "pvc"),
  material("Torlon", "Plastic / polymer", ["Fictiv"]),
  material("UHMW", "Plastic / polymer", ["Fictiv"]),
  material("UHMW PE", "Plastic / polymer", ["Xometry"]),
  material("Ultem", "Plastic / polymer", ["Fictiv"]),
  material("ULTEM 1000", "Plastic / polymer", ["Xometry"]),
  material("ULTEM 2300", "Plastic / polymer", ["Xometry"]),
];
