import { vendorSourceDocuments, type VendorSourceDocumentId } from "./vendor-source-documents";

export type EquipmentSource = {
  sourceDocumentId: VendorSourceDocumentId;
  vendor: string;
  document: string;
  documentDate: string;
  repositoryPath: string;
};

export type EquipmentSection =
  | "CNC Milling"
  | "CNC Lathe"
  | "QC & Inspection"
  | "Manual Machines"
  | "Sheet Metal"
  | "Finishing"
  | "EDM"
  | "Die Casting"
  | "Additive Manufacturing";

export type EquipmentDataSheet = {
  label: string;
  url: string;
  source: string;
};

export type VendorEquipment = {
  slug: string;
  vendor: string;
  section: EquipmentSection;
  name: string;
  makeModel: string;
  quantity: string;
  imagePath: string;
  imageSourceUrl: string;
  summary: string;
  details: {
    label: string;
    value: string;
  }[];
  fabricatorNotes: string[];
  dataSheets?: EquipmentDataSheet[];
  machineUrl: string;
  source: EquipmentSource;
};

export const equipmentSources = {
  zintilonProcessing: {
    sourceDocumentId: vendorSourceDocuments.zintilonProcessing.id,
    vendor: vendorSourceDocuments.zintilonProcessing.vendor,
    document: vendorSourceDocuments.zintilonProcessing.title,
    documentDate: vendorSourceDocuments.zintilonProcessing.documentDate,
    repositoryPath: vendorSourceDocuments.zintilonProcessing.repositoryPath,
  },
  zintilonQc: {
    sourceDocumentId: vendorSourceDocuments.zintilonQc20260123.id,
    vendor: vendorSourceDocuments.zintilonQc20260123.vendor,
    document: vendorSourceDocuments.zintilonQc20260123.title,
    documentDate: vendorSourceDocuments.zintilonQc20260123.documentDate,
    repositoryPath: vendorSourceDocuments.zintilonQc20260123.repositoryPath,
  },
  zintilonSheetMetal: {
    sourceDocumentId: vendorSourceDocuments.zintilonSheetMetal.id,
    vendor: vendorSourceDocuments.zintilonSheetMetal.vendor,
    document: vendorSourceDocuments.zintilonSheetMetal.title,
    documentDate: vendorSourceDocuments.zintilonSheetMetal.documentDate,
    repositoryPath: vendorSourceDocuments.zintilonSheetMetal.repositoryPath,
  },
  bestPrototypesEquipment: {
    sourceDocumentId: vendorSourceDocuments.bestPrototypesEquipment.id,
    vendor: vendorSourceDocuments.bestPrototypesEquipment.vendor,
    document: vendorSourceDocuments.bestPrototypesEquipment.title,
    documentDate: vendorSourceDocuments.bestPrototypesEquipment.documentDate,
    repositoryPath: vendorSourceDocuments.bestPrototypesEquipment.repositoryPath,
  },
} satisfies Record<string, EquipmentSource>;

export const equipmentSections: EquipmentSection[] = [
  "CNC Milling",
  "CNC Lathe",
  "QC & Inspection",
  "Manual Machines",
  "Sheet Metal",
  "Finishing",
  "EDM",
  "Die Casting",
  "Additive Manufacturing",
];

const millingImage = "/equipment/hermle-five-axis-cell.jpg";
const latheImage = "/equipment/cnc-turning-centers.jpg";
const sheetLaserImage = "/equipment/laser-cutting-machines.jpg";
const pressBrakeImage = "/equipment/press-brake-forming.jpg";
const inspectionImage = "/equipment/zeiss-cmm-inspection.jpg";
const finishingImage = "/equipment/welding-and-finishing.jpg";
const secondaryImage = "/equipment/sheet-metal-secondary-forming.jpg";
const weldingImage = "/equipment/sheet-metal-laser-welding-process.jpg";

const bestPrototypesSource = equipmentSources.bestPrototypesEquipment;

const hermleTechnicalData = {
  c22: {
    label: "HERMLE technical data C 22 GEN2",
    source: "HERMLE",
    url: "https://www.hermle.de/fileadmin/website/5_NEWS-UND-MEDIA/5_2_Mediathek/Technische_Daten/Englisch/hermle_technical_data_C22_GEN2_en.pdf",
  },
  c42: {
    label: "HERMLE technical data C 42 GEN2",
    source: "HERMLE",
    url: "https://www.hermle.de/fileadmin/website/5_NEWS-UND-MEDIA/5_2_Mediathek/Technische_Daten/Englisch/HERMLE_Technical_Data_C42_GEN2_EN.pdf",
  },
  c250: {
    label: "HERMLE technical data C 250 GEN2",
    source: "HERMLE",
    url: "https://www.hermleusa.net/fileadmin/website/5_NEWS-UND-MEDIA/5_2_Mediathek/Technische_Daten/Englisch/HERMLE_Technical-Data_C250-GEN2_2025_EN.pdf",
  },
  c400: {
    label: "HERMLE technical data C 400 GEN2",
    source: "HERMLE",
    url: "https://www.hermleusa.net/fileadmin/website/5_NEWS-UND-MEDIA/5_2_Mediathek/Technische_Daten/Englisch/hermle_technical_data_C400_GEN2_en.pdf",
  },
  c650: {
    label: "HERMLE technical data C 650 GEN2",
    source: "HERMLE",
    url: "https://www.hermle.de/fileadmin/website/5_NEWS-UND-MEDIA/5_2_Mediathek/Technische_Daten/Englisch/HERMLE_Technical_Data_C650_GEN2_EN.pdf",
  },
} satisfies Record<string, EquipmentDataSheet>;

const jingdiaoDataSheets = {
  jdgr200t: {
    label: "Jingdiao JDGR200T high-speed machining center",
    source: "Jingdiao",
    url: "https://en.jingdiao.com/resource/JDGR/JDGR200T.pdf",
  },
  jdgr400t: {
    label: "Jingdiao JDGR400T high-speed machining center",
    source: "Jingdiao",
    url: "https://en.jingdiao.com/resource/JDGR/JDGR400T.pdf",
  },
  jdhgt400t: {
    label: "Jingdiao JDHGT400T high-speed machining center",
    source: "Jingdiao",
    url: "https://en.jingdiao.com/resource/JDHGT/JDHGT400T.pdf",
  },
} satisfies Record<string, EquipmentDataSheet>;

function millingCard(input: Omit<VendorEquipment, "vendor" | "section" | "imagePath" | "imageSourceUrl" | "machineUrl" | "source"> & { imagePath?: string; imageSourceUrl?: string; machineUrl?: string }) {
  return {
    vendor: "Zintilon",
    section: "CNC Milling" as const,
    imagePath: input.imagePath ?? millingImage,
    imageSourceUrl: input.imageSourceUrl ?? "https://www.hermleusa.net/machining-centres-automation/models/machining-centre-c-400-gen2/",
    machineUrl: input.machineUrl ?? "https://www.hermle.de/en/machining-centres-automation/models/overview/",
    source: equipmentSources.zintilonProcessing,
    ...input,
  };
}

function latheCard(input: Omit<VendorEquipment, "vendor" | "section" | "imagePath" | "imageSourceUrl" | "machineUrl" | "source"> & { imagePath?: string; imageSourceUrl?: string; machineUrl?: string }) {
  return {
    vendor: "Zintilon",
    section: "CNC Lathe" as const,
    imagePath: input.imagePath ?? latheImage,
    imageSourceUrl: input.imageSourceUrl ?? "https://www.industrysearch.com.au/hardinge-turning-machine-gs-200/p/200045",
    machineUrl: input.machineUrl ?? "https://www.hardinge.com/turning/turning-centers/",
    source: equipmentSources.zintilonProcessing,
    ...input,
  };
}

function qcCard(input: Omit<VendorEquipment, "vendor" | "section" | "imagePath" | "imageSourceUrl" | "machineUrl" | "source"> & { imagePath?: string; imageSourceUrl?: string; machineUrl?: string }) {
  return {
    vendor: "Zintilon",
    section: "QC & Inspection" as const,
    imagePath: input.imagePath ?? inspectionImage,
    imageSourceUrl: input.imageSourceUrl ?? "https://www.zeiss.com/metrology/us/systems/cmms/bridge-type-cmms/contura.html",
    machineUrl: input.machineUrl ?? "https://www.zeiss.com/metrology/us/systems/cmms.html",
    source: equipmentSources.zintilonQc,
    ...input,
  };
}

function manualCard(input: Omit<VendorEquipment, "vendor" | "section" | "imagePath" | "imageSourceUrl" | "machineUrl" | "source"> & { imagePath?: string; imageSourceUrl?: string; machineUrl?: string; source?: EquipmentSource }) {
  return {
    vendor: "Zintilon",
    section: "Manual Machines" as const,
    imagePath: input.imagePath ?? secondaryImage,
    imageSourceUrl: input.imageSourceUrl ?? "https://www.zintilon.com/",
    machineUrl: input.machineUrl ?? "https://www.zintilon.com/",
    source: input.source ?? equipmentSources.zintilonSheetMetal,
    ...input,
  };
}

function sheetMetalCard(input: Omit<VendorEquipment, "vendor" | "section" | "imagePath" | "imageSourceUrl" | "machineUrl" | "source"> & { imagePath?: string; imageSourceUrl?: string; machineUrl?: string; source?: EquipmentSource }) {
  return {
    vendor: "Zintilon",
    section: "Sheet Metal" as const,
    imagePath: input.imagePath ?? pressBrakeImage,
    imageSourceUrl: input.imageSourceUrl ?? "https://www.zintilon.com/",
    machineUrl: input.machineUrl ?? "https://www.zintilon.com/",
    source: input.source ?? equipmentSources.zintilonSheetMetal,
    ...input,
  };
}

function finishingCard(input: Omit<VendorEquipment, "vendor" | "section" | "imagePath" | "imageSourceUrl" | "machineUrl" | "source"> & { imagePath?: string; imageSourceUrl?: string; machineUrl?: string; source?: EquipmentSource }) {
  return {
    vendor: "Zintilon",
    section: "Finishing" as const,
    imagePath: input.imagePath ?? finishingImage,
    imageSourceUrl: input.imageSourceUrl ?? "https://thermal-mech.com/product/panasonic-yc-350wx5/",
    machineUrl: input.machineUrl ?? "https://industry.panasonic.eu/welding",
    source: input.source ?? equipmentSources.zintilonProcessing,
    ...input,
  };
}

function bestPrototypesCard(
  section: EquipmentSection,
  input: Omit<VendorEquipment, "vendor" | "section" | "imagePath" | "imageSourceUrl" | "machineUrl" | "source"> & {
    imagePath?: string;
    imageSourceUrl?: string;
    machineUrl?: string;
  },
) {
  return {
    vendor: "Best Prototypes",
    section,
    imagePath: input.imagePath ?? millingImage,
    imageSourceUrl: input.imageSourceUrl ?? "https://best-prototypes.com/",
    machineUrl: input.machineUrl ?? "https://best-prototypes.com/",
    source: bestPrototypesSource,
    ...input,
  };
}

export const vendorEquipment: VendorEquipment[] = [
  millingCard({
    slug: "hermle-c400",
    name: "5-axis CNC milling machine",
    makeModel: "Hermle C400",
    quantity: "2 sets",
    imageSourceUrl: "https://www.hermleusa.net/machining-centres-automation/models/machining-centre-c-400-gen2/",
    imagePath: "/equipment/hermle-c400.jpg",
    dataSheets: [hermleTechnicalData.c400],
    summary: "High-accuracy 5-axis milling capacity for complex prismatic parts and multi-face machining.",
    details: [
      { label: "3-axis envelope", value: "850 x 700 x 500 mm" },
      { label: "5-axis envelope", value: "Dia. 650 x H500 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "18,000" },
      { label: "Control", value: "Heidenhain TNC640" },
    ],
    fabricatorNotes: ["Useful for tight-tolerance housings, manifolds, and parts needing fewer refixtures."],
  }),
  millingCard({
    slug: "hermle-c250",
    name: "5-axis CNC milling machine",
    makeModel: "Hermle C250",
    quantity: "1 set",
    imageSourceUrl: "https://www.hermleusa.net/machining-centres-automation/models/machining-centre-c-250-gen2/",
    imagePath: "/equipment/hermle-c250.jpg",
    dataSheets: [hermleTechnicalData.c250],
    summary: "Compact Hermle 5-axis platform for smaller precision components.",
    details: [
      { label: "3-axis envelope", value: "600 x 550 x 450 mm" },
      { label: "5-axis envelope", value: "Dia. 450 x H355 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "18,000" },
      { label: "Control", value: "Heidenhain TNC640" },
    ],
    fabricatorNotes: ["Good fit for smaller precision parts where 5-axis access matters more than travel."],
  }),
  millingCard({
    slug: "hermle-c42u",
    name: "5-axis CNC milling machine",
    makeModel: "Hermle C42U",
    quantity: "2 sets",
    imageSourceUrl: "https://www.hermle.de/en/machining-centres-automation/models/machining-centre-c-42-gen2/",
    imagePath: "/equipment/hermle-c42u.jpg",
    dataSheets: [hermleTechnicalData.c42],
    summary: "Mid-large 5-axis Hermle capacity with strong envelope and tolerance control.",
    details: [
      { label: "3-axis envelope", value: "800 x 800 x 550 mm" },
      { label: "5-axis envelope", value: "Dia. 800 x H560 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "18,000" },
      { label: "Control", value: "Heidenhain TNC640" },
    ],
    fabricatorNotes: ["Useful when part size and multi-axis access both drive supplier fit."],
  }),
  millingCard({
    slug: "hermle-c22u",
    name: "5-axis CNC milling machine",
    makeModel: "Hermle C22U",
    quantity: "3 sets",
    imageSourceUrl: "https://www.hermle.de/en/machining-centres-automation/models/machining-centre-c-22-gen2/",
    imagePath: "/equipment/hermle-c22u.jpg",
    dataSheets: [hermleTechnicalData.c22],
    summary: "Precision 5-axis milling capacity for smaller complex parts and repeat production.",
    details: [
      { label: "3-axis envelope", value: "450 x 600 x 330 mm" },
      { label: "5-axis envelope", value: "Dia. 450 x H370 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "18,000" },
      { label: "Control", value: "Heidenhain TNC640" },
    ],
    fabricatorNotes: ["Three listed machines improve scheduling resilience for small complex part families."],
  }),
  millingCard({
    slug: "hermle-c650",
    name: "5-axis CNC milling machine",
    makeModel: "Hermle C650",
    quantity: "1 set",
    imageSourceUrl: "https://www.hermle.de/en/machining-centres-automation/models/machining-centre-c-650-gen2/",
    imagePath: "/equipment/hermle-c650.jpg",
    dataSheets: [hermleTechnicalData.c650],
    summary: "Large-envelope Hermle 5-axis platform for bigger high-precision components.",
    details: [
      { label: "3-axis envelope", value: "1050 x 900 x 600 mm" },
      { label: "5-axis envelope", value: "Dia. 900 x H600 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "18,000" },
      { label: "Control", value: "Heidenhain TNC640" },
    ],
    fabricatorNotes: ["Best Hermle fit in this list for larger parts that still need tight tolerance and 5-axis access."],
  }),
  millingCard({
    slug: "dmg-mori-dmu-50",
    name: "5-axis CNC milling machine",
    makeModel: "Deckel Maho Gildemeister DMU 50",
    quantity: "3 sets",
    imagePath: "/equipment/dmg-mori-dmu-50.jpg",
    imageSourceUrl: "https://us.dmgmori.com/products/machines/milling/5-axis-milling/dmu/dmu-50",
    machineUrl: "https://us.dmgmori.com/products/machines/milling/5-axis-milling/dmu/dmu-50",
    summary: "Flexible DMG 5-axis capacity for prototype through production milling.",
    details: [
      { label: "3-axis envelope", value: "650 x 520 x 475 mm" },
      { label: "5-axis envelope", value: "Dia. 630 x H600 mm" },
      { label: "Best tolerance", value: "+/-0.008 mm" },
      { label: "Max RPM", value: "14,000" },
      { label: "Control", value: "Siemens 840D" },
    ],
    fabricatorNotes: ["Good fit for components with angled features, blended surfaces, or tolerance stack-up risk."],
  }),
  millingCard({
    slug: "kmc-kmc1250",
    name: "Large-format 5-axis CNC milling machine",
    makeModel: "KMC KMC1250",
    quantity: "1 set",
    imagePath: "/equipment/kede-kmc1250.jpg",
    imageSourceUrl: "http://www.51jichuang.com/equipment/151231.html",
    machineUrl: "https://www.kedecnc.com/",
    summary: "Large 5-axis equipment for parts that exceed common vertical machining center travel.",
    details: [
      { label: "3-axis envelope", value: "1200 x 1540 x 1000 mm" },
      { label: "5-axis envelope", value: "Dia. 1200 x H1000 mm" },
      { label: "Best tolerance", value: "+/-0.01 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "GNC62 bus-type 5-axis CNC" },
    ],
    fabricatorNotes: ["Use when envelope is the gating factor, not only feature complexity."],
  }),
  millingCard({
    slug: "kmc-kmc600s-umt",
    name: "5-axis CNC milling machine",
    makeModel: "KMC KMC600S UMT",
    quantity: "1 set",
    imagePath: "/equipment/kede-kmc600s-umt.jpg",
    imageSourceUrl: "https://www.pamtonschnell.com/home.php/index/buyinfo?id=20937",
    machineUrl: "https://www.kedecnc.com/",
    summary: "KMC 5-axis milling platform for smaller precision multi-axis work.",
    details: [
      { label: "3-axis envelope", value: "650 x 650 x 450 mm" },
      { label: "5-axis envelope", value: "Dia. 600 x H450 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "14,000" },
      { label: "Control", value: "GNC62" },
    ],
    fabricatorNotes: ["Strong option when the RFQ needs 5-axis capability in a compact envelope."],
  }),
  millingCard({
    slug: "kmc-kmc800s-umt",
    name: "5-axis CNC milling machine",
    makeModel: "KMC KMC800S UMT",
    quantity: "1 set",
    imagePath: "/equipment/kede-kmc800s-umt.png",
    imageSourceUrl: "http://www.51jichuang.com/equipment/151109.html",
    machineUrl: "https://www.kedecnc.com/",
    summary: "KMC 5-axis machine listed with a June 20, 2025 arrival date.",
    details: [
      { label: "Processing envelope", value: "800 x 800 x 550 mm" },
      { label: "Best tolerance", value: "+/-0.01 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "GNC62 bus-type 5-axis CNC" },
      { label: "Arrival note", value: "2025-06-20" },
    ],
    fabricatorNotes: ["Treat as planned/added capacity when quoting delivery timing."],
  }),
  millingCard({
    slug: "afming-gmu-800",
    name: "5-axis CNC milling machine",
    makeModel: "Dongguan AFMING GMU-800",
    quantity: "24 sets",
    imagePath: "/equipment/afming-gmu-800-cell.jpg",
    imageSourceUrl: "https://en.afming.com/product/82.html",
    machineUrl: "https://www.afming.com/",
    summary: "Highest-volume 5-axis group in the current Zintilon list.",
    details: [
      { label: "Processing envelope", value: "850 x 950 x 550 mm" },
      { label: "Best tolerance", value: "+/-0.008 mm" },
      { label: "Max RPM", value: "20,000" },
      { label: "Control", value: "Heidenhain TNC640" },
    ],
    fabricatorNotes: ["Twenty-four machines materially improve capacity for repeat part families."],
  }),
  millingCard({
    slug: "jingdiao-jdgr200t",
    name: "5-axis CNC milling machine",
    makeModel: "Beijing Jingdiao JDGR200T",
    quantity: "1 set",
    imageSourceUrl: "https://en.jingdiao.com/machines/high-speed-machining-centers/5-axis-series/jdgr200t",
    imagePath: "/equipment/jingdiao-jdgr200t.jpg",
    dataSheets: [jingdiaoDataSheets.jdgr200t],
    summary: "High-speed small-envelope 5-axis Jingdiao machine.",
    details: [
      { label: "3-axis envelope", value: "500 x 280 x 300 mm" },
      { label: "5-axis envelope", value: "Dia. 260 x H300 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "32,000" },
      { label: "Control", value: "JD50" },
    ],
    fabricatorNotes: ["High spindle speed makes this relevant for small fine-feature parts."],
  }),
  millingCard({
    slug: "jingdiao-jdgr400t",
    name: "5-axis CNC milling machine",
    makeModel: "Beijing Jingdiao JDGR400T",
    quantity: "4 sets",
    imageSourceUrl: "https://en.jingdiao.com/machines/high-speed-machining-centers/5-axis-series/jdgr400t",
    imagePath: "/equipment/jingdiao-jdgr400t.png",
    dataSheets: [jingdiaoDataSheets.jdgr400t],
    summary: "Jingdiao 5-axis milling capacity for small to mid-size precision parts.",
    details: [
      { label: "3-axis envelope", value: "450 x 680 x 400 mm" },
      { label: "5-axis envelope", value: "500 x H305 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "20,000" },
      { label: "Control", value: "JD50" },
    ],
    fabricatorNotes: ["Four listed machines support repeatability for smaller multi-axis components."],
  }),
  millingCard({
    slug: "guohe-mvx3205ax",
    name: "5-axis CNC milling machine",
    makeModel: "Taiwan Guohe MVX3205AX",
    quantity: "2 sets",
    imagePath: "/equipment/union-mvx320-5ax.jpg",
    imageSourceUrl: "https://www.cens.com/cens/html/en/product/product_main_177870.html",
    summary: "5-axis milling capacity with Heidenhain control for compact workpieces.",
    details: [
      { label: "3-axis envelope", value: "520 x 510 x 300 mm" },
      { label: "5-axis envelope", value: "Dia. 400 x 320 mm" },
      { label: "Best tolerance", value: "+/-0.01 mm" },
      { label: "Max RPM", value: "15,000" },
      { label: "Control", value: "Heidenhain TNC640" },
    ],
    fabricatorNotes: ["Useful for compact parts requiring 5-axis access with moderate tolerance requirements."],
  }),
  millingCard({
    slug: "shengyu-850",
    name: "CNC milling machine",
    makeModel: "Shandong Shengyu 850",
    quantity: "10 sets",
    imagePath: "/equipment/vmc850.jpg",
    imageSourceUrl: "https://www.ncmillingmachine.com/vertical-machining-center-vmc-855a-product/",
    summary: "Shared Shengyu 850 make/model listed across 5-axis and 4-axis CNC milling capacity.",
    details: [
      { label: "Processing envelope", value: "800 x 500 x 700 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "15,000" },
      { label: "Control", value: "Mitsubishi M80A" },
      { label: "Listed modes", value: "2 sets in 5-axis section; 8 sets in 4-axis section" },
    ],
    fabricatorNotes: ["This card combines identical make/model rows while preserving the listed mode split."],
  }),
  millingCard({
    slug: "taichuan-2016",
    name: "5-axis CNC milling machine",
    makeModel: "Dongguan Taichuan Taichuan 2016",
    quantity: "1 set",
    imageSourceUrl: "https://www.taichuan-tech.com/machine-overview",
    imagePath: "/equipment/taichuan-machine.jpg",
    summary: "Taichuan 5-axis milling machine for general multi-axis work.",
    details: [
      { label: "Processing envelope", value: "830 x 650 x 500 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "15,000" },
      { label: "Control", value: "Mitsubishi M80A" },
    ],
    fabricatorNotes: ["Use for lower-risk 5-axis work where tolerance demand is looser than the Hermle or Jingdiao machines."],
  }),
  millingCard({
    slug: "makino-a40",
    name: "4-axis CNC milling machine",
    makeModel: "Makino a40",
    quantity: "2 sets",
    imagePath: "/equipment/makino-four-axis-and-vmc.jpg",
    imageSourceUrl: "https://www.ide-pro.com/image/catalog/PDF/makino_a40.pdf",
    machineUrl: "https://www.makino.com/en-us/machine-technology/machines",
    summary: "Makino horizontal 4-axis milling capacity for production workholding and repeatability.",
    details: [
      { label: "Processing envelope", value: "560 x 640 x 640 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "20,000" },
      { label: "Control", value: "FS32i-B" },
    ],
    fabricatorNotes: ["Good candidate for repeat parts that benefit from horizontal fixturing."],
  }),
  millingCard({
    slug: "taichuan-640",
    name: "4-axis CNC milling machine",
    makeModel: "Dongguan Taichuan Taichuan 640",
    quantity: "10 sets",
    imageSourceUrl: "https://www.taichuan-tech.com/machine-overview",
    imagePath: "/equipment/taichuan-machine.jpg",
    summary: "High-count Taichuan 4-axis capacity for smaller milled parts.",
    details: [
      { label: "Processing envelope", value: "600 x 400 x 300 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "20,000" },
      { label: "Control", value: "Mitsubishi M80B" },
    ],
    fabricatorNotes: ["Combines duplicate Taichuan 640 rows from the equipment list into one make/model card."],
  }),
  millingCard({
    slug: "taichuan-850",
    name: "4-axis CNC milling machine",
    makeModel: "Dongguan Taichuan Taichuan 850",
    quantity: "2 sets",
    imageSourceUrl: "https://www.taichuan-tech.com/machine-overview",
    imagePath: "/equipment/taichuan-machine.jpg",
    summary: "4-axis Taichuan machine for mid-size general milling.",
    details: [
      { label: "Processing envelope", value: "800 x 500 x 500 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Mitsubishi M70B" },
    ],
    fabricatorNotes: ["Useful for moderate-size parts with standard milling tolerance requirements."],
  }),
  millingCard({
    slug: "youjia-fvp-1000a",
    name: "4-axis CNC milling machine",
    makeModel: "Hangzhou Youjia FVP-1000A",
    quantity: "6 sets",
    imagePath: "/equipment/feeler-fvp1000a.jpg",
    imageSourceUrl: "https://www.pamtonschnell.com/home.php/index/buyinfo?id=6100",
    summary: "General-purpose 4-axis milling capacity with a 1000 mm X-axis envelope.",
    details: [
      { label: "Processing envelope", value: "1000 x 500 x 450 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "10,000" },
      { label: "Control", value: "Fanuc 0i MD" },
    ],
    fabricatorNotes: ["Six listed machines support production routing for mid-size parts."],
  }),
  millingCard({
    slug: "tongzhen-taizhen-850",
    name: "4-axis CNC milling machine",
    makeModel: "Dongguan Tongzhen Taizhen 850",
    quantity: "2 sets",
    imagePath: "/equipment/taizheng-vmc850.jpg",
    imageSourceUrl: "https://www.pamtonschnell.com/home.php/index/buyinfo?id=28710",
    summary: "4-axis milling capacity for moderate envelope work.",
    details: [
      { label: "Processing envelope", value: "800 x 500 x 500 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "8,000" },
      { label: "Control", value: "Mitsubishi M70A" },
    ],
    fabricatorNotes: ["Lower spindle speed makes it more suitable for general milling than high-speed fine-feature work."],
  }),
  millingCard({
    slug: "taichuan-966",
    name: "4-axis CNC milling machine",
    makeModel: "Dongguan Taichuan Taichuan 966",
    quantity: "2 sets",
    imageSourceUrl: "https://www.taichuan-tech.com/machine-overview",
    imagePath: "/equipment/taichuan-machine.jpg",
    summary: "4-axis Taichuan capacity with a larger 900 mm X-axis travel.",
    details: [
      { label: "Processing envelope", value: "900 x 600 x 600 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Mitsubishi M80B" },
    ],
    fabricatorNotes: ["Useful for mid-size prismatic components and fixtures."],
  }),
  millingCard({
    slug: "jingdiao-jdhgt400t",
    name: "4-axis CNC milling machine",
    makeModel: "Beijing Jingdiao JDHGT400T",
    quantity: "1 set",
    imageSourceUrl: "https://en.jingdiao.com/machines/high-speed-machining-centers/3-axis-series/jdhgt400t",
    imagePath: "/equipment/jingdiao-jdhgt400t.jpg",
    dataSheets: [jingdiaoDataSheets.jdhgt400t],
    summary: "High-speed small-envelope Jingdiao machine.",
    details: [
      { label: "Processing envelope", value: "400 x 200 x 200 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "28,000" },
      { label: "Control", value: "JD50" },
    ],
    fabricatorNotes: ["Best fit for small fine-feature work where spindle speed matters."],
  }),
  millingCard({
    slug: "taichuan-tc-1580",
    name: "3-axis CNC milling machine",
    makeModel: "Dongguan Taichuan TC-1580",
    quantity: "2 sets",
    imageSourceUrl: "https://www.taichuan-tech.com/machine-overview",
    imagePath: "/equipment/taichuan-machine.jpg",
    summary: "Large 3-axis milling capacity with 1500 mm X-axis travel.",
    details: [
      { label: "Processing envelope", value: "1500 x 800 x 800 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Heidenhain" },
    ],
    fabricatorNotes: ["Use for larger plates, fixtures, and prismatic parts."],
  }),
  millingCard({
    slug: "taichuan-tc-1380",
    name: "3-axis CNC milling machine",
    makeModel: "Dongguan Taichuan TC-1380",
    quantity: "2 sets",
    imageSourceUrl: "https://www.taichuan-tech.com/machine-overview",
    imagePath: "/equipment/taichuan-machine.jpg",
    summary: "Large 3-axis milling platform with 1300 mm X-axis travel.",
    details: [
      { label: "Processing envelope", value: "1300 x 800 x 800 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Heidenhain" },
    ],
    fabricatorNotes: ["Good for large-envelope, lower-complexity machined components."],
  }),
  millingCard({
    slug: "guohe-mv1000",
    name: "3-axis CNC milling machine",
    makeModel: "Taiwan Guohe MV1000",
    quantity: "4 sets",
    imagePath: "/equipment/union-mv1000.jpg",
    imageSourceUrl: "https://www.cens.com/cens/html/en/product/product_main_177869.html",
    summary: "3-axis milling capacity for mid-size production work.",
    details: [
      { label: "Processing envelope", value: "1000 x 500 x 500 mm" },
      { label: "Best tolerance", value: "+/-0.01 mm" },
      { label: "Max RPM", value: "15,000" },
      { label: "Control", value: "Fanuc 0i MF" },
    ],
    fabricatorNotes: ["Better tolerance rating than many general 3-axis entries in the list."],
  }),
  millingCard({
    slug: "tongzhen-tv1100",
    name: "3-axis CNC milling machine",
    makeModel: "Dongguan Tongzhen T-V1100",
    quantity: "6 sets",
    imagePath: "/equipment/vmc-1166.jpg",
    imageSourceUrl: "https://avdby1.com/cnc-vertical-machining-center_nvm-1166.html",
    summary: "3-axis milling capacity with 1000 mm X-axis travel.",
    details: [
      { label: "Processing envelope", value: "1000 x 600 x 500 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Mitsubishi M70A" },
    ],
    fabricatorNotes: ["Six-machine count supports repeat work and schedule resilience."],
  }),
  millingCard({
    slug: "yangsen-ysv-1580",
    name: "3-axis CNC milling machine",
    makeModel: "Xiamen Yangsen YSV-1580",
    quantity: "2 sets",
    imagePath: "/equipment/yangsen-ysv-1580.jpg",
    imageSourceUrl: "https://greatmagtech.en.made-in-china.com/product/XZOtyeFvijUQ/China-Vertical-Machining-Centres-Ysv-1580-Vmc-Machine.html",
    summary: "Large 3-axis milling capacity for bigger plates and frames.",
    details: [
      { label: "Processing envelope", value: "1500 x 800 x 700 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Mitsubishi M80A" },
    ],
    fabricatorNotes: ["Use where 1500 mm travel is more important than 5-axis capability."],
  }),
  millingCard({
    slug: "fanuc-31i-model-b-plus",
    name: "3-axis CNC milling machine",
    makeModel: "FANUC 31i-MODEL B Plus",
    quantity: "10 sets",
    imagePath: "/equipment/fanuc-31i-model-b-plus.jpg",
    imageSourceUrl: "https://www.fanuc.co.jp/en/product/cnc/fs_30i-bplus.html",
    summary: "High-count FANUC-controlled 3-axis capacity for smaller production work.",
    details: [
      { label: "Processing envelope", value: "500 x 400 x 330 mm" },
      { label: "Best tolerance", value: "+/-0.01 mm" },
      { label: "Max RPM", value: "24,000" },
      { label: "Control", value: "Fanuc 0i MF" },
    ],
    fabricatorNotes: ["Ten-machine count and high spindle speed support repeat small-part work."],
  }),
  millingCard({
    slug: "jingrui-wh-866",
    name: "3-axis CNC milling machine",
    makeModel: "Shenzhen JingRui WH-866 (BT40)",
    quantity: "2 sets",
    imagePath: "/equipment/vmc850.jpg",
    imageSourceUrl: "https://www.ncmillingmachine.com/vertical-machining-center-vmc-855a-product/",
    summary: "3-axis milling capacity with strong tolerance listing.",
    details: [
      { label: "Processing envelope", value: "860 x 600 x 600 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Mitsubishi M80" },
    ],
    fabricatorNotes: ["One of the tighter listed 3-axis tolerance ratings."],
  }),
  millingCard({
    slug: "makino-ps105",
    name: "3-axis CNC milling machine",
    makeModel: "Makino PS105",
    quantity: "8 sets",
    imagePath: "/equipment/makino-ps105.jpg",
    imageSourceUrl: "https://www.makino.com/en-us/machine-technology/machines/vertical-machining-centers-3-axis/ps105-vertical-machining-center",
    machineUrl: "https://www.makino.com/en-us/machine-technology/machines/vertical-machining-centers-3-axis/ps105-vertical-machining-center",
    summary: "Makino vertical milling capacity for accurate repeat jobs.",
    details: [
      { label: "Processing envelope", value: "1050 x 510 x 460 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "14,000" },
      { label: "Control", value: "Fanuc 0i MF" },
    ],
    fabricatorNotes: ["Eight-machine count makes this a strong production route for precision 3-axis work."],
  }),
  millingCard({
    slug: "gromax-grm-3022x",
    name: "3-axis CNC milling machine",
    makeModel: "Gromax CNC Grm-3022X",
    quantity: "2 sets",
    imagePath: "/equipment/gromax-grm-3022x.jpg",
    imageSourceUrl: "https://cncgromax.en.made-in-china.com/product/ZJnYvIiOhCUQ/China-Gantry-Machining-Center-Gantry-CNC-Machine-3022X-Fanuc-Siemens-Mitsubishi-Controller-3-Axis-5-Axis.html",
    summary: "Very large 3-axis milling capacity for oversized components.",
    details: [
      { label: "Processing envelope", value: "3000 x 2200 x 1100 mm" },
      { label: "Best tolerance", value: "+/-0.025 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Fanuc 0i MF" },
      { label: "Arrival note", value: "2024-12-28" },
    ],
    fabricatorNotes: ["Use for oversized parts where no standard VMC envelope will work."],
  }),
  millingCard({
    slug: "jiafa-jf-m1166",
    name: "3-axis CNC milling machine",
    makeModel: "Jia Fa JF-M1166",
    quantity: "2 sets",
    imagePath: "/equipment/jtvc-1166.png",
    imageSourceUrl: "https://www.kejietechnology.com/vertical-machining-center/34",
    summary: "3-axis milling capacity listed with a 2025 arrival note.",
    details: [
      { label: "Processing envelope", value: "1100 x 600 x 500 mm" },
      { label: "Best tolerance", value: "+/-0.01 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Mitsubishi M80A" },
      { label: "Arrival note", value: "2025-07-25" },
    ],
    fabricatorNotes: ["Treat as added/planned 3-axis capacity when reviewing supplier schedule."],
  }),

  latheCard({
    slug: "shuofang-sz-325f1",
    name: "5-axis CNC Swiss-type automatic lathe",
    makeModel: "Shenzhen Shuofang SZ-325F1",
    quantity: "1 set",
    imagePath: "/equipment/shuofang-sz325f1.png",
    imageSourceUrl: "https://sowincnc.com/325f-385fshuangzhuzhoushukongzouxinji31/726.html",
    summary: "Swiss-type lathe for small cylindrical parts requiring multiple operations in one setup.",
    details: [
      { label: "Bar capacity", value: "Dia. 32 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "6,000" },
      { label: "Control", value: "Xindai 220TB" },
    ],
    fabricatorNotes: ["Good fit for pins, shafts, fittings, and smaller turned parts with milled features."],
  }),
  latheCard({
    slug: "shuofang-sz-255e1",
    name: "5-axis CNC Swiss-type automatic lathe",
    makeModel: "Shenzhen Shuofang SZ-255E1",
    quantity: "1 set",
    imagePath: "/equipment/shuofang-sz255e1.png",
    imageSourceUrl: "https://www.sowincnc.com/205e-255eshuangzhuzhoushukongzouxinji27/715.html",
    summary: "Swiss-type lathe for smaller-diameter precision turned components.",
    details: [
      { label: "Bar capacity", value: "Dia. 25 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "10,000" },
      { label: "Control", value: "Xindai 220TB" },
    ],
    fabricatorNotes: ["Higher listed spindle speed than SZ-325F1 for smaller bar work."],
  }),
  latheCard({
    slug: "shuofang-sz-206f",
    name: "6-axis CNC Swiss-type automatic lathe",
    makeModel: "Shenzhen Shuofang SZ-206F",
    quantity: "1 set",
    imagePath: "/equipment/shuofang-sz206f.jpg",
    imageSourceUrl: "https://sowincncn.en.made-in-china.com/product/cCmQizDlVJUV/China-CNC-precision-automatic-lathe-SZ-206F.html",
    summary: "6-axis Swiss-type lathe for very small turned components.",
    details: [
      { label: "Bar capacity", value: "Dia. 20 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "12,000" },
      { label: "Control", value: "Xindai 220TB" },
      { label: "Arrival note", value: "2024-12-10" },
    ],
    fabricatorNotes: ["Best suited to small shaft-like parts that benefit from Swiss turning."],
  }),
  latheCard({
    slug: "shuofang-sc-46yd",
    name: "4+4 turn-milling compound machine",
    makeModel: "Shenzhen Shuofang SC-46YD",
    quantity: "1 set",
    imagePath: "/equipment/shuofang-sc46yd.jpg",
    imageSourceUrl: "https://sowincncn.en.made-in-china.com/product/vZktsBnAlMVK/China-Precision-Metal-Turning-CNC-Lathe-Machine-SC-46YD-Horizontal-Flat-Bed-Lathe-CNC-Lathe.html",
    summary: "Turn-mill equipment for small round parts with secondary milled features.",
    details: [
      { label: "Bar capacity", value: "Dia. 45 mm" },
      { label: "Best tolerance", value: "+/-0.02 mm" },
      { label: "Max RPM", value: "6,000" },
      { label: "Control", value: "Xindai 220TB" },
      { label: "Arrival note", value: "2024-12-10" },
    ],
    fabricatorNotes: ["Good option when a turned part needs flats, cross holes, or milled features without a second setup."],
  }),
  latheCard({
    slug: "hardinge-gs-200-plus",
    name: "CNC turning center",
    makeModel: "American Hardinge GS 200 Plus",
    quantity: "2 sets",
    imagePath: "/equipment/hardinge-gs-200-plus.jpg",
    imageSourceUrl: "https://www.tuson.com/2021/06/04/gs200-plus-hardinge-cnc-single-spindle-automatic-lathe/",
    summary: "Precision turning center for smaller cylindrical components.",
    details: [
      { label: "Turning envelope", value: "Dia. 284 x 406 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "6,000" },
      { label: "Control", value: "Fanuc 0i TF" },
    ],
    fabricatorNotes: ["Useful for small turned parts needing tight concentricity and finish control."],
  }),
  latheCard({
    slug: "heideman-t55my",
    name: "CNC turning center",
    makeModel: "Heideman T55MY",
    quantity: "2 sets",
    imagePath: "/equipment/heideman-t55my.png",
    imageSourceUrl: "https://www.headmancnc.com/t55my/",
    summary: "CNC turning center for medium-diameter round parts.",
    details: [
      { label: "Turning envelope", value: "Dia. 300 x 429 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "5,000" },
      { label: "Control", value: "Siemens" },
    ],
    fabricatorNotes: ["Good fit for moderate-size turned components where tolerance control is important."],
  }),
  latheCard({
    slug: "puma-4005lm",
    name: "CNC turning center",
    makeModel: "Puma 4005LM",
    quantity: "2 sets",
    imagePath: "/equipment/puma-4005.png",
    imageSourceUrl: "https://www.i-mtf.com/mtf/PUMA_4005%5E%5E291_en.html",
    summary: "Large CNC turning capacity for bigger diameters and long shaft-like work.",
    details: [
      { label: "Turning envelope", value: "Dia. 500 x 2000 mm" },
      { label: "Best tolerance", value: "+/-0.005 mm" },
      { label: "Max RPM", value: "2,000" },
      { label: "Control", value: "Fanuc 0i TF" },
      { label: "Arrival note", value: "2025-04-01" },
    ],
    fabricatorNotes: ["Best listed option for long turned parts in the current dataset."],
  }),

  qcCard({
    slug: "zeiss-contura-7106-rds",
    name: "Coordinate measuring machine",
    makeModel: "ZEISS CONTURA 7/10/6 RDS",
    quantity: "1 set",
    imagePath: "/equipment/zeiss-contura-7106-rds.jpg",
    imageSourceUrl: "https://www.machinesused.com/machines/20",
    summary: "Calibrated ZEISS CMM for dimensional verification and formal inspection packages.",
    details: [
      { label: "Machine no.", value: "217847" },
      { label: "Next calibration", value: "2026-03-10" },
      { label: "Department", value: "QC" },
      { label: "Calibration agency", value: "Shenzhen Huaxin Measurement Testing Co., Ltd." },
    ],
    fabricatorNotes: ["Use for RFQs requiring CMM reports, FAI-style evidence, or tolerance-critical features."],
  }),
  qcCard({
    slug: "zeiss-contura-7106",
    name: "Coordinate measuring machine",
    makeModel: "ZEISS CONTURA 7/10/6",
    quantity: "5 sets",
    imagePath: "/equipment/zeiss-contura.jpg",
    imageSourceUrl: "https://www.oriontec.co.jp/COUNTURA.html",
    summary: "Core ZEISS bridge CMM capacity for repeat dimensional inspection.",
    details: [
      { label: "Machine nos.", value: "234500, 425223061983, 243754, 243758, 425224062756" },
      { label: "Calibration status", value: "2025 and 2026 dates listed" },
      { label: "Department", value: "QC" },
      { label: "Calibration agencies", value: "Shenzhen Huaxin and Carl Zeiss" },
    ],
    fabricatorNotes: ["Combines the same make/model across separate machine numbers into one equipment-type card."],
  }),
  qcCard({
    slug: "zeiss-contura-12188",
    name: "Coordinate measuring machine",
    makeModel: "ZEISS CONTURA 12/18/8",
    quantity: "1 set",
    imagePath: "/equipment/zeiss-contura.jpg",
    imageSourceUrl: "https://www.oriontec.co.jp/COUNTURA.html",
    summary: "Larger ZEISS CONTURA CMM for bigger inspected parts.",
    details: [
      { label: "Machine no.", value: "425224072816" },
      { label: "Next calibration", value: "2025-08-21" },
      { label: "Department", value: "QC" },
      { label: "Calibration agency", value: "Carl Zeiss" },
    ],
    fabricatorNotes: ["Important for larger CNC parts where a smaller CMM envelope may not be enough."],
  }),
  qcCard({
    slug: "zeiss-accura-9168",
    name: "Coordinate measuring machine",
    makeModel: "ZEISS ACCURA 9/16/8",
    quantity: "1 set",
    imagePath: "/equipment/zeiss-accura-9168.jpg",
    imageSourceUrl: "https://shop.metrology.zeiss.de/INTERSHOP/web/WFS/IMT-DE-Site/de_DE/-/EUR/ViewProduct-Start?SKU=600099-2830-054",
    summary: "ZEISS ACCURA CMM for high-confidence dimensional inspection.",
    details: [
      { label: "Machine no.", value: "218198" },
      { label: "Next calibration", value: "2026-05-28" },
      { label: "Department", value: "QC" },
      { label: "Calibration agency", value: "Shenzhen Huaxin Measurement Testing Co., Ltd." },
    ],
    fabricatorNotes: ["Useful when inspection depth is a deciding factor for tolerance-critical awards."],
  }),
  qcCard({
    slug: "fengkang-vmc432",
    name: "Automatic image measuring instrument",
    makeModel: "Fengkang Precision VMC432",
    quantity: "1 set",
    imagePath: "/equipment/tztek-vmc432.png",
    imageSourceUrl: "https://www.machinetools.com/en/models/tztek-vmc432",
    summary: "Vision measurement equipment for optical dimensional checks.",
    details: [
      { label: "Spec", value: "400 x 300 x 200 mm" },
      { label: "Machine no.", value: "FW20180305002" },
      { label: "Next calibration", value: "2026-05-28" },
      { label: "Department", value: "QC" },
    ],
    fabricatorNotes: ["Useful for small features and optical checks that do not require tactile CMM probing."],
  }),
  qcCard({
    slug: "feile-smu-4030ef",
    name: "Automatic image measuring instrument",
    makeModel: "FEILE SMU-4030EF",
    quantity: "1 set",
    imagePath: "/equipment/vms-4030f-vision-measurement.jpg",
    imageSourceUrl: "https://www.bonnin-instruments.com/quality-47920024-vms-4030f-image-measurement-instrument-3d-cnc-video-measuring-system",
    summary: "Automatic image measuring system for optical inspection.",
    details: [
      { label: "Spec", value: "300 x 400 mm" },
      { label: "Machine no.", value: "82799019485" },
      { label: "Next calibration", value: "2025-08-30" },
      { label: "Department", value: "QC" },
    ],
    fabricatorNotes: ["Adds redundant vision inspection capacity for small sheet or machined features."],
  }),
  qcCard({
    slug: "oxford-xmet7500",
    name: "X-ray material analyzer",
    makeModel: "Oxford Instruments X-MET7500",
    quantity: "1 set",
    imagePath: "/equipment/oxford-xmet7500.jpg",
    imageSourceUrl: "https://romquest.com/product/oxford-x-met7500-handheld-xrf-analyser/",
    machineUrl: "https://hha.hitachi-hightech.com/en/product-range/products/handheld-xrf-libs-analyzers/handheld-xrf-analyzers",
    summary: "Handheld XRF analyzer for alloy verification and material screening.",
    details: [
      { label: "Machine no.", value: "751562" },
      { label: "Next calibration", value: "2026-03-17" },
      { label: "Department", value: "QC" },
      { label: "Use case", value: "Positive material identification" },
    ],
    fabricatorNotes: ["Helpful for confirming stainless, aluminum, copper, brass, and alloy identity."],
  }),
  qcCard({
    slug: "libo-uee941",
    name: "Surface roughness tester",
    makeModel: "Chongqing Libo Uee 941",
    quantity: "1 set",
    imagePath: "/equipment/surface-roughness-tester.jpg",
    imageSourceUrl: "https://www.ato.com/portable-digital-surface-roughness-tester",
    summary: "Surface finish verification tool for machined or finished parts.",
    details: [
      { label: "Machine no.", value: "16122813" },
      { label: "Next calibration", value: "2025-08-30" },
      { label: "Department", value: "QC" },
      { label: "Note", value: "Calibrated with a standard" },
    ],
    fabricatorNotes: ["Relevant for RFQs with Ra/Rz requirements or visible finish expectations."],
  }),
  qcCard({
    slug: "mitutoyo-calipers",
    name: "Digital and dial calipers",
    makeModel: "Mitutoyo 0-150 / 0-200 / 0-300 mm calipers",
    quantity: "30+ sets",
    imagePath: "/equipment/mitutoyo-calipers.jpg",
    imageSourceUrl: "https://cuttingtoolpickers.com/products/0-6-digital-caliper-mitutoyo-500-196-30",
    machineUrl: "https://www.mitutoyo.com/products/small-tool-instruments-and-data-management/calipers/",
    summary: "Shop-floor and QC caliper coverage for routine dimensional checks.",
    details: [
      { label: "Ranges", value: "0-150, 0-200, and 0-300 mm" },
      { label: "Departments", value: "QC, CNC production, sheet metal, handwork, lathe" },
      { label: "Calibration status", value: "2025 and 2026 dates listed" },
    ],
    fabricatorNotes: ["Aggregated by make/model family because the source lists many duplicate calipers by serial number."],
  }),
  qcCard({
    slug: "mahr-tesa-height-gauges",
    name: "Height measuring instruments",
    makeModel: "TESA / Mahr digital height gauges",
    quantity: "6+ sets",
    imagePath: "/equipment/mahr-height-gauge.jpg",
    imageSourceUrl: "https://www.mahr.com/en-us/news-events/article-view/mahr-inc-unveils-highly-precise-intuitive-digimar-817-clt-height-measuring-device",
    machineUrl: "https://metrology.mahr.com/en-int/solutions/engineered/products/dimensional-metrology/",
    summary: "Height gauges for shop-floor and QC dimensional inspection.",
    details: [
      { label: "Ranges", value: "0-600 and 0-700 mm" },
      { label: "Brands", value: "TESA and Mahr" },
      { label: "Departments", value: "QC, CNC production, sheet metal" },
    ],
    fabricatorNotes: ["Useful for formed sheet metal and machined feature height checks."],
  }),

  manualCard({
    slug: "xihu-swj-16",
    name: "Bench tapping machine",
    makeModel: "Xihu SWJ-16",
    quantity: "1 set",
    imageSourceUrl: "https://wdmwdm.en.made-in-china.com/product/SKrmoEsChnWp/China-SWJ-Series-Tapping-Machine-SWJ-16.html",
    imagePath: "/equipment/swj-16-tapping.jpg",
    summary: "Bench tapping machine for secondary threaded holes in sheet metal parts.",
    details: [
      { label: "Tapping capacity", value: "Within M16" },
      { label: "Source row", value: "Sheet Metal Equipment List item 5" },
    ],
    fabricatorNotes: ["Call out tapped holes during RFQ intake because they add a secondary routing step."],
  }),
  manualCard({
    slug: "xihu-z516a",
    name: "Bench drilling machine",
    makeModel: "Xihu Z516A",
    quantity: "2 sets",
    imageSourceUrl: "https://www.smt-machinery.com/15-inch-benchtop-drill-press-16mm.html",
    imagePath: "/equipment/z516a-drill.jpg",
    summary: "Bench drilling capacity for countersink and secondary hole operations.",
    details: [
      { label: "Countersink capacity", value: "Within M16" },
      { label: "Source row", value: "Sheet Metal Equipment List item 6" },
    ],
    fabricatorNotes: ["Relevant for parts that need secondary countersinking after cutting or forming."],
  }),
  manualCard({
    slug: "xihu-zq4116",
    name: "Drilling machine",
    makeModel: "Xihu ZQ4116",
    quantity: "1 set",
    imageSourceUrl: "https://www.smt-machinery.com/15-inch-benchtop-drill-press-16mm.html",
    imagePath: "/equipment/z516a-drill.jpg",
    source: equipmentSources.zintilonProcessing,
    summary: "Additional drilling machine listed in the broader processing equipment list.",
    details: [
      { label: "Voltage note", value: "380V" },
      { label: "Listed section", value: "Drilling Machine" },
    ],
    fabricatorNotes: ["Supports secondary hole work alongside the sheet metal drilling capacity."],
  }),
  manualCard({
    slug: "xihu-s3st-250",
    name: "Bench grinder",
    makeModel: "Xihu S3ST-250",
    quantity: "1 set",
    imagePath: "/equipment/s3st-250-bench-grinder.png",
    imageSourceUrl: "https://techno.my/products/s3st-250-1-1kw-heavy-duty-pedestal-bench-grinder",
    summary: "Bench grinding support for manual sharpening and cleanup work.",
    details: [
      { label: "Capability", value: "Drill sharpener" },
      { label: "Source row", value: "Sheet Metal Equipment List item 4" },
    ],
    fabricatorNotes: ["Manual support equipment, not primary capacity, but useful context for shop-floor readiness."],
  }),

  sheetMetalCard({
    slug: "eeike-mk3015f",
    name: "Laser cutting machine",
    makeModel: "Eeike MK3015F 3000W",
    quantity: "1 set",
    imagePath: sheetLaserImage,
    imageSourceUrl: "https://us.hanslaser.net/products/fly3015-fiber-laser-cutting-machine-35.html",
    machineUrl: "https://www.hansyueming.com/FiberLaserCuttingMachine_115.html",
    summary: "3015-format sheet laser for flat profiles, brackets, panels, and blanks.",
    details: [
      { label: "Processing range", value: "1500 x 3000 mm" },
      { label: "Power", value: "3000 W" },
      { label: "Material capacity", value: "Iron 15 mm; aluminum 8 mm; stainless 10 mm; copper/brass within 6 mm" },
      { label: "Listed accuracy", value: "Aperture +/-0.05 mm; trimming +/-0.1 mm" },
    ],
    fabricatorNotes: ["Use for sheet metal parts where thickness and edge profile drive routing."],
  }),
  sheetMetalCard({
    slug: "dazu-mps3015c",
    name: "Laser cutting machine",
    makeModel: "Dazu MPS3015C 6000W",
    quantity: "1 set",
    imagePath: "/equipment/dazu-mps3015c.jpg",
    imageSourceUrl: "https://www.hansmplaser.com/products/detail-18.html",
    machineUrl: "https://www.hansmplaser.com/products/detail-18.html",
    summary: "Higher-power 3015-format laser listed in the sheet metal capability deck.",
    details: [
      { label: "Processing range", value: "1500 x 3000 mm" },
      { label: "Power", value: "6000 W" },
      { label: "Material capacity", value: "Iron 25 mm; aluminum 16 mm; stainless 20 mm; copper/brass within 12 mm" },
      { label: "Listed accuracy", value: "Aperture +/-0.05 mm; trimming +/-0.1 mm" },
    ],
    fabricatorNotes: ["Best listed laser option for thicker sheet and plate in the sheet metal deck."],
  }),
  sheetMetalCard({
    slug: "hans-laser-3015-6000w",
    name: "Laser cutting machine",
    makeModel: "Han's Laser 3015 6000W",
    quantity: "1 set",
    imagePath: sheetLaserImage,
    imageSourceUrl: "https://us.hanslaser.net/products/fly3015-fiber-laser-cutting-machine-35.html",
    machineUrl: "https://www.hanslaser.net/",
    source: equipmentSources.zintilonProcessing,
    summary: "Fiber laser listed in the broader processing equipment list.",
    details: [
      { label: "Processing range", value: "1500 x 3000 mm" },
      { label: "Best tolerance", value: "+/-0.1 mm" },
      { label: "Power", value: "6000 W" },
    ],
    fabricatorNotes: ["This may overlap operationally with the Dazu 6000W entry; kept separate because make/model differs in source."],
  }),
  sheetMetalCard({
    slug: "meike-3015-3000w",
    name: "Laser cutting machine",
    makeModel: "Meike 3015 3000W",
    quantity: "1 set",
    imagePath: sheetLaserImage,
    imageSourceUrl: "https://us.hanslaser.net/products/fly3015-fiber-laser-cutting-machine-35.html",
    source: equipmentSources.zintilonProcessing,
    summary: "3000W 3015 laser cutting machine from the processing equipment list.",
    details: [
      { label: "Processing range", value: "1500 x 3000 mm" },
      { label: "Best tolerance", value: "+/-0.1 mm" },
      { label: "Power", value: "3000 W" },
    ],
    fabricatorNotes: ["Useful for flat blanking and profiles before forming."],
  }),
  sheetMetalCard({
    slug: "eko-es3512",
    name: "Bending machine",
    makeModel: "EKO ES3512",
    quantity: "4 sets",
    imagePath: "/equipment/eko-es3512.jpg",
    imageSourceUrl: "https://www.dplasers.com/ES3512-35ton-1200mm-6-axis-CNC-Press-Brake-for-Sheet-metal-pd42529559.html",
    machineUrl: "https://www.dplasers.com/ES3512-35ton-1200mm-6-axis-CNC-Press-Brake-for-Sheet-metal-pd42529559.html",
    source: equipmentSources.zintilonProcessing,
    summary: "Short-bed press brake capacity for sheet metal forming.",
    details: [
      { label: "Forming length", value: "1200 mm" },
      { label: "Best tolerance", value: "+/-0.1 mm" },
      { label: "Sheet metal deck note", value: "35T-100T within 3 m; bending accuracy +/-0.2 mm" },
    ],
    fabricatorNotes: ["Good for smaller bent brackets, covers, and formed details."],
  }),
  sheetMetalCard({
    slug: "eko-es1003",
    name: "Bending machine",
    makeModel: "EKO ES1003",
    quantity: "1 set",
    imagePath: pressBrakeImage,
    imageSourceUrl: "https://www.dplasers.com/ES3512-35ton-1200mm-6-axis-CNC-Press-Brake-for-Sheet-metal-pd42529559.html",
    source: equipmentSources.zintilonProcessing,
    summary: "Longer EKO bending machine for wider sheet metal work.",
    details: [
      { label: "Forming length", value: "3000 mm" },
      { label: "Best tolerance", value: "+/-0.1 mm" },
      { label: "Sheet metal deck note", value: "35T-100T within 3 m; bending accuracy +/-0.2 mm" },
    ],
    fabricatorNotes: ["Use where part width requires a longer bend length."],
  }),
  sheetMetalCard({
    slug: "haiji-eg6520",
    name: "Bending machine",
    makeModel: "Hai Ji EG6520",
    quantity: "1 set",
    imagePath: pressBrakeImage,
    imageSourceUrl: "https://www.dplasers.com/ES3512-35ton-1200mm-6-axis-CNC-Press-Brake-for-Sheet-metal-pd42529559.html",
    source: equipmentSources.zintilonProcessing,
    summary: "Mid-length bending machine for sheet metal forming.",
    details: [
      { label: "Forming length", value: "2000 mm" },
      { label: "Best tolerance", value: "+/-0.1 mm" },
      { label: "Sheet metal deck note", value: "35T-100T within 3 m; bending accuracy +/-0.2 mm" },
    ],
    fabricatorNotes: ["Middle option between the 1200 mm and 3000 mm bend-length machines."],
  }),
  sheetMetalCard({
    slug: "yike-ehc2203",
    name: "Bending machine",
    makeModel: "Yi Ke EHC2203",
    quantity: "1 set",
    imagePath: pressBrakeImage,
    imageSourceUrl: "https://www.dplasers.com/ES3512-35ton-1200mm-6-axis-CNC-Press-Brake-for-Sheet-metal-pd42529559.html",
    source: equipmentSources.zintilonProcessing,
    summary: "3000 mm bending machine listed with a February 26, 2025 arrival date.",
    details: [
      { label: "Forming length", value: "3000 mm" },
      { label: "Best tolerance", value: "+/-0.1 mm" },
      { label: "Arrival note", value: "2025-02-26" },
    ],
    fabricatorNotes: ["Treat as added capacity for wide formed parts."],
  }),
  sheetMetalCard({
    slug: "htes-300ssb",
    name: "Oil press machine",
    makeModel: "HTES-300SSB",
    quantity: "1 set",
    imagePath: secondaryImage,
    imageSourceUrl: "https://www.zintilon.com/",
    summary: "Hydraulic press capacity for convex hull and formed features.",
    details: [
      { label: "Processing range", value: "900 x 1200 mm" },
      { label: "Press capacity", value: "300T" },
      { label: "Capability", value: "Convex hull forming within 900 x 1200 mm" },
    ],
    fabricatorNotes: ["Relevant for formed sheet details that cannot be handled by simple press brake bending."],
  }),
  sheetMetalCard({
    slug: "haiji-h618",
    name: "Riveting machine",
    makeModel: "Hai Ji H618",
    quantity: "2 sets",
    imagePath: secondaryImage,
    imageSourceUrl: "https://www.zintilon.com/",
    summary: "Press riveting equipment for clinch hardware and extracted features.",
    details: [
      { label: "Capacity", value: "6T" },
      { label: "Capabilities", value: "Press riveting, hole extraction, bud extraction" },
      { label: "Arrival note", value: "2025-01-15 in processing equipment list" },
    ],
    fabricatorNotes: ["Important for sheet metal parts requiring PEM-style hardware or formed bosses."],
  }),
  sheetMetalCard({
    slug: "haiji-h518",
    name: "Riveting machine",
    makeModel: "Hai Ji H518",
    quantity: "1 set",
    imagePath: secondaryImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonProcessing,
    summary: "Additional riveting machine listed in the processing equipment list.",
    details: [
      { label: "Listed section", value: "Riveting Machine" },
      { label: "Use case", value: "Sheet metal fastening and joining support" },
    ],
    fabricatorNotes: ["Kept separate from H618 because make/model differs."],
  }),
  sheetMetalCard({
    slug: "haiji-h1024",
    name: "Riveting machine",
    makeModel: "Hai Ji H1024",
    quantity: "1 set",
    imagePath: secondaryImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonProcessing,
    summary: "Additional riveting capacity listed with a January 15, 2025 arrival note.",
    details: [
      { label: "Arrival note", value: "2025-01-15" },
      { label: "Use case", value: "Sheet metal fastening and joining support" },
    ],
    fabricatorNotes: ["Useful for sheet metal assembly operations after cutting and forming."],
  }),

  finishingCard({
    slug: "chengxuan-3000w-dual-wire",
    name: "Welding machine",
    makeModel: "Chengxuan 3000W 4-in-1 Dual Wire Feeding",
    quantity: "1 set",
    imagePath: weldingImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonProcessing,
    summary: "3000W welding station for sheet metal and fabricated assembly joining.",
    details: [
      { label: "Power", value: "3000 W" },
      { label: "Listed section", value: "Welding Machine" },
    ],
    fabricatorNotes: ["Consider splitting welding into its own top-level section if the catalog grows."],
  }),
  finishingCard({
    slug: "panasonic-yc-350wx5",
    name: "Welding machine",
    makeModel: "Panasonic YC-350WX5",
    quantity: "1 set",
    imagePath: finishingImage,
    imageSourceUrl: "https://thermal-mech.com/product/panasonic-yc-350wx5/",
    source: equipmentSources.zintilonProcessing,
    summary: "Panasonic welding machine listed with a July 9, 2025 arrival note.",
    details: [
      { label: "Arrival note", value: "2025-07-09" },
      { label: "Listed section", value: "Welding Machine" },
    ],
    fabricatorNotes: ["Relevant for welded sheet metal assemblies and repair/fit-up work."],
  }),
  finishingCard({
    slug: "baonuoyang-bem-350",
    name: "Carbon dioxide gas shielded welding machine",
    makeModel: "Bao Nuo Yang BEM-350",
    quantity: "1 set",
    imagePath: weldingImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonSheetMetal,
    summary: "CO2 shielded welding capacity for larger welds and thicker fabricated parts.",
    details: [
      { label: "Capability", value: "High efficiency; can weld large welding products" },
      { label: "Process fit", value: "Thick plates, square tube frames, and large welds" },
      { label: "Tradeoff", value: "Flying slag and deformation risk after welding" },
    ],
    fabricatorNotes: ["Best represented as Welding & Joining in a future section split."],
  }),
  finishingCard({
    slug: "baonuoyang-bem-35011",
    name: "Argon arc welding machine",
    makeModel: "Bao Nuo Yang BEM-35011",
    quantity: "1 set",
    imagePath: weldingImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonSheetMetal,
    summary: "Argon arc welding station for aluminum, stainless, iron, and brass.",
    details: [
      { label: "Material capacity", value: "Aluminum, stainless steel, iron, brass within 10 mm" },
      { label: "Process fit", value: "Commonly used; suitable for thick copper, iron, aluminum, stainless steel parts" },
      { label: "Tradeoff", value: "Slower efficiency and larger deformation risk" },
    ],
    fabricatorNotes: ["Good when weld strength matters more than cosmetic no-polish output."],
  }),
  finishingCard({
    slug: "hero-aft-300",
    name: "Inverter AC/DC argon welding machine",
    makeModel: "HERO AFT-300",
    quantity: "1 set",
    imagePath: weldingImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonProcessing,
    summary: "Argon welding machine with water tank listed in the processing equipment list.",
    details: [
      { label: "Model note", value: "HERO AFT-300 inverter AC/DC argon welding machine + water tank" },
      { label: "Listed section", value: "Welding Machine" },
    ],
    fabricatorNotes: ["Separate from BEM-35011 because the make/model differs."],
  }),
  finishingCard({
    slug: "lanuss-lsg-gb1000",
    name: "Automatic grinding machine",
    makeModel: "Lanuss LSG-GB1000",
    quantity: "1 set",
    imagePath: secondaryImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonProcessing,
    summary: "Automatic grinding support for cleanup and consistent finishing.",
    details: [
      { label: "Arrival note", value: "2025-07-19" },
      { label: "Listed section", value: "Automatic Grinding Machine" },
    ],
    fabricatorNotes: ["Useful after welding or laser cutting where cosmetic cleanup matters."],
  }),
  finishingCard({
    slug: "manual-wire-brushing-machine",
    name: "Manual wire brushing machine",
    makeModel: "Manual wire brushing machine",
    quantity: "1 set",
    imagePath: secondaryImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonSheetMetal,
    summary: "Manual finishing support for brushing and surface cleanup.",
    details: [
      { label: "Source row", value: "Sheet Metal Equipment List item 14" },
      { label: "Use case", value: "Manual surface preparation and finish cleanup" },
    ],
    fabricatorNotes: ["Should be considered part of finishing rather than primary fabrication capacity."],
  }),
  finishingCard({
    slug: "sanders",
    name: "Sander",
    makeModel: "Sander",
    quantity: "4 sets",
    imagePath: secondaryImage,
    imageSourceUrl: "https://www.zintilon.com/",
    source: equipmentSources.zintilonSheetMetal,
    summary: "Sanding capacity for weld cleanup, deburring support, and surface preparation.",
    details: [
      { label: "Source row", value: "Sheet Metal Equipment List item 15" },
      { label: "Use case", value: "Polishing, cleanup, and finishing support" },
    ],
    fabricatorNotes: ["Important for cosmetic sheet metal work and post-weld surface prep."],
  }),
  bestPrototypesCard("CNC Milling", {
    slug: "best-prototypes-gf700u",
    name: "5-axis machining center",
    makeModel: "GF700U",
    quantity: "3 sets",
    imagePath: millingImage,
    summary: "Best Prototypes 5-axis milling capacity for precision prototype and production machining.",
    details: [
      { label: "Brand / origin", value: "GF, Switzerland" },
      { label: "Envelope", value: "700 x 630 x 500 mm" },
      { label: "Max RPM", value: "20,000" },
      { label: "Machining accuracy", value: "+/-0.01 mm" },
    ],
    fabricatorNotes: ["Source PDF lists 200 operators/people for the machine-tool equipment section; this is kept as vendor-provided context, not a machine-specific headcount."],
  }),
  bestPrototypesCard("CNC Milling", {
    slug: "best-prototypes-efmi-high-speed-five-axis",
    name: "High-speed 5-axis machining center",
    makeModel: "EFMI high-speed 5-axis machining center",
    quantity: "19 sets",
    imagePath: millingImage,
    summary: "High-count 5-axis machining capacity from Best Prototypes for complex milled components.",
    details: [
      { label: "Brand / origin", value: "EFMI, China" },
      { label: "Envelope", value: "700 x 1000 x 550 mm" },
      { label: "Max RPM", value: "20,000" },
      { label: "Machining accuracy", value: "+/-0.01 mm" },
      { label: "Repeatability", value: "0.004 mm" },
    ],
    fabricatorNotes: ["Useful as a high-capacity 5-axis routing option; confirm machine availability before quoting large programs."],
  }),
  bestPrototypesCard("CNC Milling", {
    slug: "best-prototypes-jingdiao-five-axis",
    name: "5-axis Jingdiao machining centers",
    makeModel: "SmartCNC500-DRTD / JDGR400-A13S / JDCT800T",
    quantity: "11 sets",
    imagePath: millingImage,
    imageSourceUrl: "https://en.jingdiao.com/",
    machineUrl: "https://en.jingdiao.com/",
    summary: "Aggregated Beijing Jingdiao 5-axis machining centers listed by Best Prototypes.",
    details: [
      { label: "Models", value: "SmartCNC500-DRTD, JDGR400-A13S, JDCT800T" },
      { label: "Envelope range", value: "450 x 680 x 400 mm to 800 x 800 x 350 mm" },
      { label: "Max RPM", value: "24,000 to 28,000" },
      { label: "Machining accuracy", value: "+/-0.02 mm" },
    ],
    fabricatorNotes: ["Aggregated to avoid duplicate cards while preserving the source model families."],
  }),
  bestPrototypesCard("CNC Milling", {
    slug: "best-prototypes-three-axis-vmc-fleet",
    name: "3-axis vertical machining center fleet",
    makeModel: "FANUC Robodrill / Chenggong / Siemens / Mitsubishi VMCs",
    quantity: "40+ sets",
    imagePath: millingImage,
    summary: "Broad 3-axis VMC capacity covering small and mid-size machined parts.",
    details: [
      { label: "Representative envelopes", value: "600 x 500 x 350 mm through 1100 x 600 x 600 mm" },
      { label: "Max RPM range", value: "10,000 to 24,000" },
      { label: "Machining accuracy", value: "+/-0.01 to +/-0.02 mm where listed" },
      { label: "Positioning / repeatability", value: "0.005 to +/-0.003 mm where listed" },
    ],
    fabricatorNotes: ["Grouped because the source lists many similar VMC rows across brands and model numbers."],
  }),
  bestPrototypesCard("CNC Lathe", {
    slug: "best-prototypes-meike-cnc-lathe",
    name: "CNC lathe and turn-mill machines",
    makeModel: "Meike CNC lathe / turning-milling composite",
    quantity: "10 sets",
    imagePath: latheImage,
    summary: "Best Prototypes turning and turn-mill capacity for round components.",
    details: [
      { label: "Machine families", value: "Meike CNC Lathe and Meike Turning-Milling Composite" },
      { label: "Listed accuracy", value: "0.01 mm" },
    ],
    fabricatorNotes: ["Source does not provide turning envelope; verify chuck size, bar capacity, and live-tooling details before quote routing."],
  }),
  bestPrototypesCard("EDM", {
    slug: "best-prototypes-middle-wire-edm",
    name: "Middle wire EDM",
    makeModel: "Middle Wire EDM",
    quantity: "5 sets",
    imagePath: secondaryImage,
    summary: "Wire EDM support for precision profiles and hard-material cutting.",
    details: [{ label: "Listed accuracy", value: "0.01 mm" }],
    fabricatorNotes: ["Use for thin slots, sharp internal profiles, and materials or geometry better suited to EDM than milling."],
  }),
  bestPrototypesCard("QC & Inspection", {
    slug: "best-prototypes-cmm-fleet",
    name: "CMM inspection fleet",
    makeModel: "ZEISS / HEXAGON / Leader 3D measuring machines",
    quantity: "4 sets",
    imagePath: inspectionImage,
    imageSourceUrl: "https://www.zeiss.com/metrology/us/systems/cmms.html",
    machineUrl: "https://www.zeiss.com/metrology/us/systems/cmms.html",
    summary: "CMM inspection capacity listed by Best Prototypes for dimensional verification.",
    details: [
      { label: "Machines", value: "ZEISS 800 x 600 x 1000, HEXAGON 700 x 600 x 1000, Leader 600 x 800 x 600" },
      { label: "Precision", value: "0.001 mm" },
    ],
    fabricatorNotes: ["Customer-facing inspection claims should still be tied to the RFQ inspection plan and certificate package."],
  }),
  bestPrototypesCard("Die Casting", {
    slug: "best-prototypes-die-casting",
    name: "Die casting equipment",
    makeModel: "Aluminum, zinc, and magnesium die casting fleet",
    quantity: "23 sets",
    imagePath: secondaryImage,
    summary: "Die casting capacity across aluminum, zinc, and magnesium alloy parts.",
    details: [
      { label: "Aluminum alloy die casting", value: "15 sets, 180T-1650T, few grams to 15 kg" },
      { label: "Zinc alloy die casting", value: "6 sets, 18T-200T" },
      { label: "Magnesium alloy die casting", value: "2 sets, 350T-400T" },
      { label: "Melting furnace", value: "1T and 1.5T center smelting furnace, 2 sets" },
    ],
    fabricatorNotes: ["New equipment section created from Best Prototypes source; tooling assumptions should be captured separately during RFQ intake."],
  }),
  bestPrototypesCard("Additive Manufacturing", {
    slug: "best-prototypes-sla-printing",
    name: "SLA 3D printing equipment",
    makeModel: "SLA450 / SLA600 / SLA800 / SLA1400 / SLA9400 fleet",
    quantity: "108 sets",
    imagePath: secondaryImage,
    summary: "Large SLA fleet for prototype resin parts across several build envelopes.",
    details: [
      { label: "Build envelopes", value: "Up to 1370 x 670 x 498 mm listed" },
      { label: "Largest listed platform", value: "SLA1400, 1400 x 700 x 500 mm equipment spec" },
      { label: "Highest-count model", value: "SLA9400, 78 sets" },
    ],
    fabricatorNotes: ["Good fit for fast visual prototypes; material and tolerance requirements must be confirmed before presenting as production-equivalent."],
  }),
  bestPrototypesCard("Additive Manufacturing", {
    slug: "best-prototypes-slm-hp-nylon-printing",
    name: "SLM and HP nylon 3D printing equipment",
    makeModel: "SLM AlSi10Mg / SLM 316L / HP nylon printers",
    quantity: "13 sets",
    imagePath: secondaryImage,
    summary: "Metal and nylon additive capacity listed by Best Prototypes.",
    details: [
      { label: "SLM materials", value: "AlSi10Mg and Stainless steel 316L" },
      { label: "SLM max product size", value: "250 x 250 x 300 mm" },
      { label: "HP nylon materials", value: "Black nylon, white nylon, color nylon" },
      { label: "HP max product size", value: "Up to 380 x 280 x 380 mm listed" },
    ],
    fabricatorNotes: ["Treat material properties, finish, and post-processing as external-source data until verified against current vendor process sheets."],
  }),
];
