import { vendorSourceDocuments, type VendorSourceDocumentId } from "./vendor-source-documents";

export type MaterialOfferingCategory =
  | "Aluminum"
  | "Carbon / Alloy Steel"
  | "Stainless Steel"
  | "Nickel / Cobalt Alloy"
  | "Controlled Expansion / Precision Alloy"
  | "Titanium"
  | "Copper / Brass / Bronze"
  | "Magnesium / Zinc"
  | "Plastics / Polymers";

export type VendorMaterialOffering = {
  vendor: string;
  category: MaterialOfferingCategory;
  forms: string[];
  grades: string[];
  sourceDocumentIds: VendorSourceDocumentId[];
  sourceNote: string;
  sourcePageRefs?: string[];
  externalDataNote?: string;
};

export const vendorMaterialOfferings: VendorMaterialOffering[] = [
  {
    vendor: "Zintilon",
    category: "Aluminum",
    forms: ["Machined stock", "Project-specific material procurement"],
    grades: [
      "Al 1070",
      "Al 2A12",
      "Al 2024",
      "Al 2014-T6",
      "Al 2024-T351",
      "Al 2014-T651",
      "Al 2024-T3",
      "Al 2014",
      "Al 2017",
      "Al 2017-T4",
      "Al 3003",
      "Al 5052-H32",
      "Al 5083",
      "Al 6060",
      "Al 6060-T6",
      "Al 6063",
      "Al 2A14",
      "Al 6063-T6",
      "Al 6061",
      "Al 6061-T6",
      "Al 6061-T651",
      "Al 6082 / AlMgSi1",
      "Al 6082-T6",
      "Al 6082-T651",
      "Al 7075",
      "Al 7075-T6",
      "Al MIC-6",
      "A413",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Extracted from the Aluminium column in Zintilon's general materials spreadsheet.",
    sourcePageRefs: ["Materials sheet, Aluminium column"],
  },
  {
    vendor: "Zintilon",
    category: "Carbon / Alloy Steel",
    forms: ["Machined stock", "Sheet metal stock", "Tool steel stock"],
    grades: [
      "17-4PH H900 Steel",
      "Steel 4140",
      "Steel 4340",
      "Steel 1.4404",
      "Steel 1045 / 45#",
      "Steel 1010",
      "Steel 1020",
      "Steel 4130",
      "Steel 1215",
      "Steel 1.2085",
      "Steel 20#",
      "Q235",
      "S355",
      "A2 Steel",
      "1018 Steel",
      "X160CrMoV12",
      "44W Steel",
      "16MnCrS5",
      "ST TOOL M2",
      "SS400",
      "18CrNiMo7-6 / 1.6587",
      "40CrNiMo",
      "FE510 Steel",
      "SKD11",
      "1.0737",
      "EN19",
      "Toolox 33",
      "1.0718",
      "S355J2",
      "1.2510 / 100MnCrW4",
      "Z160CVD12",
      "AISI 1010",
      "42CD4",
      "S15C",
      "1.033",
      "C22",
      "40CrMnMoS8-6 / 1.2312",
      "Steel S355JR",
      "SPCC",
      "SPHC",
      "SGCC",
      "SECC",
      "SPTE",
      "Steel 12L14",
      "05Cr17Ni4Cu4Nb",
      "1018S",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Normalized from the two Steel columns in Zintilon's spreadsheet.",
    sourcePageRefs: ["Materials sheet, Steel columns"],
  },
  {
    vendor: "Zintilon",
    category: "Stainless Steel",
    forms: ["Machined stock", "Sheet metal stock"],
    grades: [
      "SS 416",
      "SS 304 / 1.4301",
      "SS 303",
      "SS 316 / 1.4404",
      "SS 316L",
      "SS 17-4PH",
      "SS 304L",
      "SS 1.4305",
      "SS 420",
      "SS 430",
      "1.2085",
      "SS 440C",
      "817M40T",
      "15-5PH",
      "SS 630",
      "SS 304H",
      "SS 316H",
      "SS 18-8",
      "EN 1.4005",
      "20Cr13",
      "40Cr13",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Extracted from the Stainless Steel column in Zintilon's general materials spreadsheet.",
    sourcePageRefs: ["Materials sheet, Stainless Steel column"],
  },
  {
    vendor: "Zintilon",
    category: "Nickel / Cobalt Alloy",
    forms: ["Project-specific material procurement"],
    grades: ["Inconel 617", "Inconel 718", "Inconel 625 / Alloy 625", "Hastelloy C-22", "Hastelloy C-276", "Monel K500", "Alloy 230"],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Extracted from the Other Metal column in Zintilon's general materials spreadsheet.",
    sourcePageRefs: ["Materials sheet, Other Metal column"],
  },
  {
    vendor: "Zintilon",
    category: "Controlled Expansion / Precision Alloy",
    forms: ["Project-specific material procurement"],
    grades: ["Invar36 Alloy"],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Extracted from the Other Metal column in Zintilon's general materials spreadsheet.",
    sourcePageRefs: ["Materials sheet, Other Metal column"],
  },
  {
    vendor: "Zintilon",
    category: "Titanium",
    forms: ["Project-specific material procurement"],
    grades: ["Titanium", "TC4", "TA6V", "6AL4V"],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Extracted from the Other Metal column in Zintilon's general materials spreadsheet.",
    sourcePageRefs: ["Materials sheet, Other Metal column"],
  },
  {
    vendor: "Zintilon",
    category: "Copper / Brass / Bronze",
    forms: ["Project-specific material procurement"],
    grades: [
      "Red Copper C110",
      "Red Copper C101",
      "Red Copper",
      "Brass",
      "CuZn39Pb3",
      "Red Copper T2",
      "Brass H62",
      "Brass H59",
      "Brass C3600",
      "QSN6.5-0.1 / CuSn6",
      "QSN6-6-3 / CuSn6Zn6",
      "Beryllium Copper",
      "Bronze",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Extracted from the Other Metal column in Zintilon's general materials spreadsheet.",
    sourcePageRefs: ["Materials sheet, Other Metal column"],
  },
  {
    vendor: "Zintilon",
    category: "Magnesium / Zinc",
    forms: ["Project-specific material procurement"],
    grades: ["Magnesium", "AZ91D", "AM60B", "AZ31B", "Zamak 3", "Zamak 5 / ASTM AC41A", "ZN"],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Extracted from the Other Metal column in Zintilon's general materials spreadsheet.",
    sourcePageRefs: ["Materials sheet, Other Metal column"],
  },
  {
    vendor: "Zintilon",
    category: "Plastics / Polymers",
    forms: ["Machined plastics", "Prototype resin", "Composite-filled polymer stock"],
    grades: [
      "ABS Black / White",
      "ABS+30% GF",
      "ABS+30% PC",
      "Flame Retardant ABS",
      "PMMA",
      "POM / Delrin",
      "POM-C",
      "POM-H",
      "POM+30%GF",
      "PC",
      "PC+ABS/T85",
      "PC+30%GF",
      "Fire-Resistant PC",
      "PC + PU8400 Overmolded",
      "PA / Nylon",
      "Nylon 6",
      "Nylon 66",
      "PA12",
      "PA+30%GF",
      "PA66+30%GF",
      "PA12+30%GF",
      "PA+13%GF",
      "PA+15%GF",
      "PA+20%GF",
      "PA66+20%GF",
      "PU8400",
      "PU8150",
      "PVC",
      "PP",
      "PP+20%GF",
      "PP+30%GF",
      "PE",
      "PPS",
      "PPS+30%GF",
      "PPS+40%GF",
      "PEEK",
      "PEI",
      "PBT",
      "PETP",
      "PPSU",
      "HDPE",
      "HDPE 1000",
      "TEFLON",
      "UHMW",
      "Carbon Fibre",
      "Fibre glass",
      "Bakelite Resin",
      "PX527",
      "PX521",
      "PVDF",
      "EPDM",
      "ULTEM 1000",
      "ASTM D6100",
      "PX233 HT",
      "Photopolymer Resin",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zintilonMaterials20250613.id],
    sourceNote: "Normalized from the two Plastics columns in Zintilon's spreadsheet.",
    sourcePageRefs: ["Materials sheet, Plastics columns"],
  },
  {
    vendor: "Saky Steel",
    category: "Nickel / Cobalt Alloy",
    forms: ["Wire", "Strip", "Bar", "Sheet", "Pipe", "Forging", "Flange"],
    grades: [
      "Inconel 600",
      "Inconel 601",
      "Inconel 625",
      "Inconel 690",
      "Inconel 718",
      "Inconel X-750",
      "Incoloy 800",
      "Incoloy 800H",
      "Incoloy 800HT",
      "Incoloy 825",
      "Incoloy A-286",
      "Incoloy 925",
      "Nickel 200",
      "Nickel 201",
      "Monel 400",
      "Monel K-500",
      "Hastelloy C-276",
      "Hastelloy C-22",
      "Hastelloy B-2",
      "Hastelloy X",
    ],
    sourceDocumentIds: [vendorSourceDocuments.sakyCatalog.id],
    sourceNote: "Extracted from Saky catalog table of contents and material pages.",
    sourcePageRefs: ["Catalog pages 7-23"],
  },
  {
    vendor: "Saky Steel",
    category: "Controlled Expansion / Precision Alloy",
    forms: ["Wire", "Strip", "Bar", "Sheet", "Pipe", "Forging", "Flange"],
    grades: ["1J50", "1J79", "1J85", "4J32", "Kovar / 4J29", "Invar36"],
    sourceDocumentIds: [vendorSourceDocuments.sakyCatalog.id],
    sourceNote: "Extracted from Saky precision alloy section and material pages.",
    sourcePageRefs: ["Catalog pages 24-26"],
  },
  {
    vendor: "Saky Steel",
    category: "Stainless Steel",
    forms: ["Wire", "Strip", "Bar", "Sheet", "Pipe", "Forging", "Flange"],
    grades: ["904L", "Alloy 20", "253MA", "254SMO", "Duplex 2205 / S31803", "Duplex 2205 / S32205", "Super Duplex 2507", "Z100 / S32760"],
    sourceDocumentIds: [vendorSourceDocuments.sakyCatalog.id],
    sourceNote: "Extracted from Saky 904L/Alloy 20 and duplex stainless sections.",
    sourcePageRefs: ["Catalog pages 27-35"],
  },
  {
    vendor: "Tianjin ZYTC Alloy Technology Co., Ltd",
    category: "Nickel / Cobalt Alloy",
    forms: ["Sheet", "Plate", "Strip", "Bar", "Rod", "Seamless pipe", "Tube", "Welded pipe", "Forging"],
    grades: [
      "Alloy 25 / L605",
      "Alloy 188",
      "Alloy 20",
      "Alloy 28",
      "Alloy 230",
      "Alloy 242",
      "Alloy 263",
      "Alloy 282",
      "Alloy 556",
      "Alloy 617",
      "Alloy 625",
      "Alloy 718",
      "Alloy S",
      "Waspaloy",
      "Alloy X",
      "Alloy X-750",
      "Alloy B-3",
      "Alloy C-4",
      "Alloy C-22",
      "Alloy C-276",
      "Alloy G-30",
      "Alloy G-35",
      "Alloy N",
      "Alloy 600",
      "Alloy 601",
      "Alloy 800",
      "Alloy 800H",
      "Alloy 800HT",
      "Alloy 725",
      "Alloy A286",
      "Alloy 200",
      "Alloy 201",
      "Alloy 400",
      "Alloy K500",
      "MP159",
      "MP35N",
      "Alloy 686",
      "Alloy 80A",
      "Alloy R41",
      "R31537",
      "Alloy 925",
      "Nimonic 300",
      "AerMet 100",
      "Multimet N155",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zytcCatalogue.id],
    sourceNote: "Transcribed from the ZYTC image-based catalog nickel/cobalt alloy tables.",
    sourcePageRefs: ["Catalog image pages 11-12"],
  },
  {
    vendor: "Tianjin ZYTC Alloy Technology Co., Ltd",
    category: "Controlled Expansion / Precision Alloy",
    forms: ["Sheet", "Plate", "Strip", "Bar", "Rod", "Wire", "Forging"],
    grades: ["Kovar", "Invar 36"],
    sourceDocumentIds: [vendorSourceDocuments.zytcCatalogue.id],
    sourceNote: "Transcribed from the ZYTC image-based nickel/cobalt alloy table rows for Kovar and Invar.",
    sourcePageRefs: ["Catalog image page 12"],
  },
  {
    vendor: "Tianjin ZYTC Alloy Technology Co., Ltd",
    category: "Stainless Steel",
    forms: ["Sheet", "Plate", "Strip", "Bar", "Rod", "Pipe", "Tube", "Wire", "Forging"],
    grades: [
      "301",
      "302",
      "303",
      "303Se",
      "303Sulf",
      "304",
      "304L",
      "304LVM",
      "309",
      "310",
      "310S",
      "316",
      "316L",
      "316LVM",
      "316Ti",
      "321",
      "330 / RA330",
      "347",
      "347H",
      "410",
      "410Mod",
      "420",
      "430",
      "430F",
      "430FR",
      "431",
      "440C",
      "Custom 455",
      "Nitronic 40",
      "Nitronic 50",
      "Nitronic 60",
      "Duplex F51",
      "Duplex F55",
      "15-5PH",
      "13-8PH",
      "17-4PH",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zytcCatalogue.id],
    sourceNote: "Transcribed from the ZYTC image-based catalog stainless steel tables.",
    sourcePageRefs: ["Catalog image pages 13-16"],
  },
  {
    vendor: "Tianjin ZYTC Alloy Technology Co., Ltd",
    category: "Titanium",
    forms: ["Sheet", "Plate", "Bar", "Rod", "Pipe", "Tube", "Wire", "Forging", "Ring"],
    grades: [
      "Grade 1",
      "Grade 2",
      "Grade 3",
      "Grade 4",
      "Grade 5 / 6Al-4V",
      "Grade 6 / 5Al-2.5Sn",
      "Grade 7",
      "Grade 9 / 3Al-2.5V",
      "Grade 12",
      "6Al-2Sn-4Zr-2Mo",
      "6Al-6V-2Sn",
      "6Al-7Nb",
      "8Al-1Mo-1V",
    ],
    sourceDocumentIds: [vendorSourceDocuments.zytcCatalogue.id],
    sourceNote: "Transcribed from the ZYTC image-based catalog titanium tables.",
    sourcePageRefs: ["Catalog image pages 17-18"],
  },
  {
    vendor: "Tianjin ZYTC Alloy Technology Co., Ltd",
    category: "Carbon / Alloy Steel",
    forms: ["Sheet", "Plate", "Bar", "Rod", "Forging"],
    grades: ["4130", "4140 Annealed", "4140 Normalized", "4330 Mod VM N&T", "4340 / E4340", "52100", "6150 Vac Melt Annealed", "9310 / E9310", "300M VAR / E4340 Mod"],
    sourceDocumentIds: [vendorSourceDocuments.zytcCatalogue.id],
    sourceNote: "Transcribed from the ZYTC image-based catalog alloy steel tables.",
    sourcePageRefs: ["Catalog image pages 19-20"],
  },
];

export function getMaterialOfferingsByVendor(vendor: string) {
  return vendorMaterialOfferings.filter((offering) => offering.vendor === vendor);
}

